import test from 'node:test';import assert from 'node:assert/strict';import {harness,fixture} from './game-harness.mjs';
test('all seven cities change the playable venues and survive save reloads',()=>{const t=harness({...fixture(),money:100000,rankClaimed:6});const cities=Object.keys(t.game.cityData);assert.equal(cities.length,7);for(let i=0;i<cities.length;i++){const money=t.game.state.money,from=t.game.state.city;t.game.trips();t.click('trip-'+i);assert.equal(t.game.state.city,cities[i]);if(from!==cities[i]){assert.equal(t.game.state.money,money-t.game.cityData[cities[i]].fare);assert.equal(t.game.state.place,'station')}for(const id of ['night','african','church','plaza'])assert.ok(t.game.locations.find(p=>p[0]===id));const loaded=harness(JSON.parse(JSON.stringify(t.game.state)));assert.equal(loaded.game.state.city,cities[i]);assert.equal(loaded.game.locations.find(p=>p[0]==='night')[1],t.game.cityData[cities[i]].names.night)}assert.equal(t.game.state.trips.length,6)});
test('intercity travel rejects insufficient funds and does not reset daily limits',()=>{const t=harness({...fixture(),money:0});t.game.trips();t.click('trip-1');assert.equal(t.game.state.city,'Shenyang');const raw=JSON.parse(JSON.stringify(t.game.state));raw.city='Unknown';assert.throws(()=>t.game.loadSave(raw));raw.city='Guangzhou';raw.paidActivities={'cafe:1':1};t.game.loadSave(raw);assert.equal(t.game.state.paidActivities['cafe:1'],1)});
test('phone apps include shared activities and external apps use intentional links',()=>{const t=harness();let cloud=false,chat=false,together=false,opened; t.context.ChinaLifeCloud={open:()=>cloud=true};t.context.ChinaLifeSocial={open:()=>chat=true};t.context.ChinaLifeShared={open:()=>together=true};t.context.open=(url)=>opened=url; t.game.phone();assert.equal(t.document.querySelectorAll('.phone-app[data-phone]').length,23);assert.equal(t.document.querySelectorAll('.phone-widget[data-phone]').length,2);assert.equal(t.document.querySelector('[data-phone="whatsapp"]'),null,'no WhatsApp app');for(const key of ['together','people','hafrik']){t.game.phone();t.document.querySelector('.phone-app[data-phone="'+key+'"]').onclick();if(key==='together')assert(together);if(key==='people')assert(chat);if(key==='hafrik')assert.equal(t.document.querySelector('#activityContent a').href,'https://hafrik.com/get')}
 t.game.phone();const search=t.document.getElementById('phoneSearch');search.value='wall';search.oninput({target:search});assert.ok([...t.document.querySelectorAll('.phone-app')].filter(b=>!b.hidden).every(b=>b.dataset.name.includes('wall')))});

test('inactive cities are omitted from travel and flight lists',()=>{
 const t=harness({...fixture(),city:'Harbin',place:'station',money:100000},{openCities:['Shenyang']});assert.equal(t.game.state.city,'Shenyang');assert.equal(t.game.state.place,'home');
 t.game.trips();assert.doesNotMatch(t.document.getElementById('activityContent').textContent,/Coming soon|Harbin|Beijing/);const harbin=Object.keys(t.game.cityData).indexOf('Harbin');assert.equal(t.document.getElementById('trip-'+harbin),null);assert.equal(t.game.state.city,'Shenyang');assert.equal(t.game.state.money,100000);
 t.game.state.place='airport';t.game.flights();assert.doesNotMatch(t.document.getElementById('activityContent').textContent,/Coming soon|Harbin|Beijing/);assert.equal(t.document.getElementById('flight-0'),null);assert.equal(t.game.state.flightBookings.length,0);
});

test('opening a city from the server makes it travelable',()=>{
 const t=harness({...fixture(),money:100000},{openCities:['Shenyang']});const harbin=Object.keys(t.game.cityData).indexOf('Harbin');t.game.trips();assert.equal(t.document.getElementById('trip-'+harbin),null);assert.equal(t.game.state.city,'Shenyang');
 t.game.setOpenCities(['Shenyang','Harbin']);t.game.trips();t.click('trip-'+harbin);assert.equal(t.game.state.city,'Harbin');
});
