import test from 'node:test';import assert from 'node:assert/strict';import {harness,fixture} from './game-harness.mjs';
test('all seven cities change the playable venues and survive save reloads',()=>{const t=harness({...fixture(),money:100000,rankClaimed:6});const cities=Object.keys(t.game.cityData);assert.equal(cities.length,7);for(let i=0;i<cities.length;i++){const money=t.game.state.money,from=t.game.state.city;t.game.trips();t.click('trip-'+i);assert.equal(t.game.state.city,cities[i]);if(from!==cities[i]){assert.equal(t.game.state.money,money-t.game.cityData[cities[i]].fare);assert.equal(t.game.state.place,'station')}for(const id of ['night','african','church','plaza'])assert.ok(t.game.locations.find(p=>p[0]===id));const loaded=harness(JSON.parse(JSON.stringify(t.game.state)));assert.equal(loaded.game.state.city,cities[i]);assert.equal(loaded.game.locations.find(p=>p[0]==='night')[1],t.game.cityData[cities[i]].names.night)}assert.equal(t.game.state.trips.length,6)});
test('intercity travel rejects insufficient funds and does not reset daily limits',()=>{const t=harness({...fixture(),money:0});t.game.trips();t.click('trip-1');assert.equal(t.game.state.city,'Shenyang');const raw=JSON.parse(JSON.stringify(t.game.state));raw.city='Unknown';assert.throws(()=>t.game.loadSave(raw));raw.city='Guangzhou';raw.paidActivities={'cafe:1':1};t.game.loadSave(raw);assert.equal(t.game.state.paidActivities['cafe:1'],1)});
test('phone apps include shared activities and external apps use intentional links',()=>{const t=harness();let cloud=false,chat=false,together=false,opened; t.context.ChinaLifeCloud={open:()=>cloud=true};t.context.ChinaLifeSocial={open:()=>chat=true};t.context.ChinaLifeShared={open:()=>together=true};t.context.open=(url)=>opened=url; t.game.phone();assert.equal(t.document.querySelectorAll('.phone-app[data-phone]').length,21);assert.equal(t.document.querySelectorAll('.phone-widget[data-phone]').length,2);for(const key of ['together','chat','hafrik','whatsapp']){t.game.phone();t.document.querySelector('[data-phone="'+key+'"]').onclick();if(key==='together')assert(together);if(key==='chat')assert(chat);if(key==='hafrik')assert.equal(t.document.querySelector('#activityContent a').href,'https://hafrik.com');if(key==='whatsapp'){const input=t.document.getElementById('whatsappNumber'),form=t.document.getElementById('whatsappForm');input.value='invalid';form.onsubmit({preventDefault(){}});assert.equal(opened,undefined);input.value='+234 801 234 5678';form.onsubmit({preventDefault(){}});assert.equal(opened,'https://wa.me/2348012345678')}}});

test('launch opens only Shenyang and lists the other cities as coming soon',()=>{
 const t=harness({...fixture(),city:'Harbin',place:'station',money:100000},{openCities:['Shenyang']});assert.equal(t.game.state.city,'Shenyang');assert.equal(t.game.state.place,'home');
 t.game.trips();assert.match(t.document.getElementById('activityContent').textContent,/Coming soon/);const harbin=Object.keys(t.game.cityData).indexOf('Harbin');t.click('trip-'+harbin);assert.equal(t.game.state.city,'Shenyang');assert.equal(t.game.state.money,100000);
 t.game.state.place='airport';t.game.flights();assert.match(t.document.getElementById('activityContent').textContent,/Coming soon/);t.click('flight-0');assert.equal(t.game.state.flightBookings.length,0);
});

test('opening a city from the server makes it travelable',()=>{
 const t=harness({...fixture(),money:100000},{openCities:['Shenyang']});const harbin=Object.keys(t.game.cityData).indexOf('Harbin');t.game.trips();t.click('trip-'+harbin);assert.equal(t.game.state.city,'Shenyang');
 t.game.setOpenCities(['Shenyang','Harbin']);t.game.trips();t.click('trip-'+harbin);assert.equal(t.game.state.city,'Harbin');
});
