import test from 'node:test';import assert from 'node:assert/strict';import {harness,fixture} from './game-harness.mjs';
test('fresh character creation, name validation, background and isolated defaults',()=>{const h=harness(null);assert(h.document.getElementById('onboarding').open);h.click('nextStep');assert.match(h.document.getElementById('toast').textContent,/begins/);h.document.querySelector('[data-start="inside"]').onclick();h.click('nextStep');h.click('nextStep');assert.match(h.document.getElementById('toast').textContent,/role/);h.document.querySelector('[data-role="Student"]').onclick();h.click('nextStep');h.click('nextStep');assert.match(h.document.getElementById('toast').textContent,/name/);h.document.getElementById('onName').oninput({target:{value:'Adewale'}});h.click('nextStep');assert.equal(h.game.state.name,'Adewale');assert.equal(h.game.state.skills.Study,2);assert.equal(h.game.state.created,true);assert(!h.document.getElementById('onboarding').open);assert(h.writes.length>0)});
test('corrupt saves recover and blocked local storage does not break play',()=>{const corrupt=harness(null,{raw:'{broken'});assert(corrupt.document.getElementById('onboarding').open);assert.match(corrupt.document.getElementById('toast').textContent,/could not be loaded/);const blocked=harness(fixture(),{blockStorage:true});blocked.game.activity('home',0);assert.equal(blocked.game.state.hour,700);assert.match(blocked.document.getElementById('toast').textContent,/slept/)});
test('location activities require travel; free actions remain available in debt',()=>{const h=harness();h.game.activity('ef',0);assert.equal(h.game.state.money,3200);h.game.state.place='park';h.game.state.money=-100;h.game.activity('park',0);assert.equal(h.game.state.money,-100);assert.equal(h.game.state.stats.activities,1);assert.equal(h.game.state.hour,580)});
test('activity durations, affordability and needs bounds',()=>{const h=harness();assert.equal(h.internal.duration('3h · free'),180);assert.equal(h.internal.duration('90m'),90);h.game.state.needs.energy=99;h.game.activity('home',0);assert.equal(h.game.state.needs.energy,100);h.game.state.money=1;const before=h.game.state.hour;h.game.activity('home',1);assert.equal(h.game.state.hour,before)});
test('phone Jobs exposes current shift and six application controls',()=>{const h=harness({...fixture(),job:'cafe-job'});h.game.phone();h.document.querySelector('[data-phone="jobs"]').onclick();assert(h.document.getElementById('currentJob'));assert.equal(h.document.querySelectorAll('[data-job]').length,6);h.click('currentJob');assert(h.document.getElementById('goWork'))});
test('job prerequisites, next-day start, work location and daily pay limit',()=>{const h=harness();h.internal.jobsDialog();h.document.querySelector('[data-job="designer"]').onclick();assert.equal(h.game.state.job,null);h.document.querySelector('[data-job="cafe-job"]').onclick();assert.equal(h.game.state.jobStart,2);h.internal.workShift('steady');assert.equal(h.game.state.money,3200);h.game.state.place='cafe';h.internal.workShift('steady');assert.equal(h.game.state.money,3200);h.internal.advance(1440);h.game.state.needs.energy=80;h.game.state.needs.hunger=80;h.internal.workShift('focus');assert.equal(h.game.state.money,3384);h.internal.workShift('steady');assert.equal(h.game.state.money,3384)});
test('paid cafe activity cannot bypass a career shift; freelance has daily limit',()=>{const h=harness({...fixture(),place:'cafe'});h.game.activity('cafe',0);assert.equal(h.game.state.money,3200);h.game.activity('cafe',1);assert.equal(h.game.state.money,3285);h.game.activity('cafe',1);assert.equal(h.game.state.money,3285);const restored=h.internal.validateSave(JSON.parse(JSON.stringify(h.game.state)));assert.equal(restored.paidActivities['cafe:1'],1)});
test('travel charges virtual money and exhausted players can return home',()=>{const h=harness();h.game.travel('gym');h.click('metroTravel');assert.equal(h.game.state.place,'gym');assert.equal(h.game.state.money,3196);h.game.state.money=-100;h.game.state.needs.energy=0;h.game.travel('home');h.click('walkTravel');assert.equal(h.game.state.place,'home');assert.equal(h.game.state.money,-100);assert.match(h.document.getElementById('activityContent').textContent,/You fainted/);assert.equal(h.game.state.needs.energy,20)});
test('home operations cannot teleport; pantry prevents hunger deadlock',()=>{const h=harness({...fixture(),place:'gym',money:-100});h.game.home();assert(h.document.getElementById('goHome'));assert(!h.document.getElementById('homeRest'));h.game.state.place='home';h.game.state.needs.hunger=0;h.game.home();h.click('pantryMeal');assert.equal(h.game.state.needs.hunger,35);assert(!h.document.getElementById('pantryMeal'))});
test('furniture charges once, desk trains skills and sleep advances day correctly',()=>{const h=harness();h.game.home();h.click('buy-bed');assert.equal(h.game.state.money,2750);h.click('buy-bed');assert.equal(h.game.state.money,2750);h.click('buy-desk');h.click('homeStudy');assert.equal(h.game.state.skillXP.Study,25);const day=h.game.state.day;h.click('homeRest');assert.equal(h.game.state.day,day+1);assert.equal(h.game.state.hour,480);assert.equal(h.game.state.needs.energy,100)});
test('weekly rent is charged once on day rollover',()=>{const h=harness({...fixture(),day:6,hour:1439});h.internal.advance(1);assert.equal(h.game.state.day,7);assert.equal(h.game.state.money,2600);h.internal.advance(1);assert.equal(h.game.state.money,2600)});
test('NPC conversation location and daily limits preserve friendship rewards',()=>{const h=harness();assert.equal(h.internal.talkNPC('mei',0),false);h.game.state.place='campus';assert.equal(h.internal.talkNPC('mei',1),true);assert.equal(h.game.state.friends.mei,15);assert.equal(h.game.state.skillXP.Chinese,20);assert.equal(h.internal.talkNPC('mei',2),false);assert.equal(h.game.state.friends.mei,15)});
test('event venue, time, invalid choices and daily cooldown',()=>{const h=harness();assert.equal(h.internal.attendEvent(0),false);h.game.state.place='ef';assert.equal(h.internal.attendEvent(0),false);h.game.state.hour=1080;assert.equal(h.internal.attendEvent(5),false);assert.equal(h.internal.attendEvent(0),true);assert.equal(h.internal.attendEvent(0),false)});
test('quests and dream rewards can only be claimed once',()=>{const h=harness({...fixture(),visited:['home','ef','park','gym','cafe']});assert.equal(h.internal.claimQuest('payday'),false);assert.equal(h.internal.claimQuest('explorer'),true);assert.equal(h.game.state.money,3320);assert.equal(h.internal.claimQuest('explorer'),false);h.game.state.xp=400;h.game.state.upgrades=['bed','desk','kitchen'];assert.equal(h.internal.claimDream(),true);assert.equal(h.internal.claimDream(),false)});
test('studio launch, location, daily orders and expansion requirements',()=>{const h=harness();assert.equal(h.internal.launchBusiness(),false);h.game.state.skills.Network=2;h.game.state.skills.Digital=2;assert.equal(h.internal.launchBusiness(),true);assert.equal(h.internal.launchBusiness(),false);assert.equal(h.internal.fulfilOrder(),false);h.game.state.place='business';assert.equal(h.internal.fulfilOrder(),true);assert.equal(h.internal.fulfilOrder(),false);assert.equal(h.internal.growBusiness(),false)});
test('all thirteen phone apps route to their actual screen',()=>{const h=harness();let cloud=false;h.context.ChinaLifeCloud={open:()=>cloud=true};for(const key of ['jobs','people','skills','goals','events','studio','travel','home','journal','wallet','needs','settings','cloud']){h.game.phone();const b=h.document.querySelector('[data-phone="'+key+'"]');assert(b,key);b.onclick();if(key!=='cloud')assert(h.document.getElementById('activityDialog').open,key);else assert(cloud)} });
test('all appearance controls update the saved character',()=>{const h=harness();h.game.appearance();h.click('hair-cap');assert.equal(h.game.state.appearance.hair,'cap');h.click('skin0');assert.equal(h.game.state.appearance.skin,'#603c2c');h.click('outfit1');assert.equal(h.game.state.color,'#426dba')});
test('save import preserves progress and closes initial setup',()=>{const h=harness(null);h.game.loadSave({...fixture(),name:'Restored'});assert.equal(h.game.state.name,'Restored');assert(!h.document.getElementById('onboarding').open);assert.throws(()=>h.game.loadSave({...fixture(),money:'bad'}));assert.equal(h.game.state.name,'Restored')});

test('homes and the home desk follow the player role',()=>{
 const student=harness({...fixture(),background:'Student'});assert.equal(student.game.locations.find(p=>p[0]==='home')[1],'Your student dorm');
 const founder=harness({...fixture(),background:'Entrepreneur',money:50000});assert.equal(founder.game.locations.find(p=>p[0]==='home')[1],'Your city apartment');
 founder.game.shop('properties','villa');assert.match(founder.document.getElementById('activityContent').textContent,/Penthouse villa/);
 founder.game.home();founder.click('buy-desk');founder.click('homeStudy');assert.equal(founder.game.state.skillXP.Network,25);
 const tourist=harness({...fixture(),background:'Tourist'});assert.equal(tourist.game.locations.find(p=>p[0]==='home')[1],'Your hotel room');
});

test('Learn lists every skill with places that teach it, and courses raise new skills',()=>{
 const h=harness({...fixture(),money:5000});h.game.state.background='Worker';h.internal.skillsScreen();const text=h.document.getElementById('activityContent').textContent;
 for(const skill of ['Chinese','Cooking','Music','Digital'])assert.match(text,new RegExp(skill));assert.match(text,/Shenyang Skills Academy/);
 h.document.querySelector('[data-learn="academy"]').onclick();h.game.state.place='academy';h.game.activity('academy',2);assert.equal(h.game.state.skillXP.Cooking,20);
 const saved=harness(JSON.parse(JSON.stringify(h.game.state)));assert.equal(saved.game.state.skillXP.Cooking,20);
});

test('ranks pay once per rank-up and the daily streak grows on consecutive days',()=>{
 const h=harness({...fixture(),xp:150,rankClaimed:0,money:1000});h.game.state.xp=250;h.internal.render();assert.equal(h.game.state.rankClaimed,1);assert.equal(h.game.state.money,1500);h.internal.render();assert.equal(h.game.state.money,1500);
 h.game.state.xp=4000;h.internal.render();assert.equal(h.game.state.rankClaimed,4);assert.equal(h.game.state.money,1500+1000+1500+2000);
 const yesterday=new Date(Date.now()-864e5).toISOString().slice(0,10),d=harness({...fixture(),lastVisit:yesterday,streak:3,money:0,rankClaimed:6});
 d.game.claimDaily();assert.equal(d.game.state.streak,4);assert.equal(d.game.state.money,200);d.game.claimDaily();assert.equal(d.game.state.money,200);
 const restored=harness(JSON.parse(JSON.stringify(d.game.state)));assert.equal(restored.game.state.streak,4);assert.equal(restored.game.state.lastVisit,new Date().toISOString().slice(0,10));
 const old=harness({...fixture(),xp:5000});assert.equal(old.game.state.rankClaimed,4);
});

test('fainting costs time, asking for food helps once a day, and gigs pay once a day',()=>{
 const h=harness({...fixture(),money:0});const hour=h.game.state.hour;h.game.state.needs.hunger=0;h.internal.render();
 assert.match(h.document.getElementById('activityContent').textContent,/You fainted/);assert.equal(h.game.state.hour,hour+90);
 h.click('faintAsk');assert.equal(h.game.state.needs.hunger,40);h.game.state.needs.hunger=0;h.internal.render();h.click('faintAsk');assert.equal(h.game.state.needs.hunger,0);
 h.game.state.needs.hunger=60;h.game.state.needs.energy=80;h.game.earn();h.click('gig-tutor');assert.equal(h.game.state.money,80);h.click('gig-tutor');assert.equal(h.game.state.money,80);
 const saved=harness(JSON.parse(JSON.stringify(h.game.state)));assert.equal(saved.game.state.gigs.tutor,h.game.state.day);
});
test('unaffordable activities open Make money and Today lists what is due',()=>{
 const h=harness({...fixture(),money:5,place:'mall'});h.game.activity('mall',0);assert.match(h.document.getElementById('activityContent').textContent,/Make money/);
 const tasks=h.game.todayTasks().map(t=>t[1]).join(' | ');assert.match(tasks,/Low on money/);assert.match(tasks,/Rent/);h.game.tasks();assert.match(h.document.getElementById('activityContent').textContent,/Today/);
});

test('a ready daily reward shows a notification banner that opens Rank',()=>{
 const h=harness({...fixture(),lastVisit:'2000-01-01'});h.internal.render();for(const fn of [...h.timers])if(typeof fn==='function')fn();const banner=h.document.getElementById('gameNotification');assert.ok(banner,'banner');assert.match(banner.textContent,/daily reward/);banner.onclick();assert.match(h.document.getElementById('activityContent').textContent,/Claim daily reward/);
});
