import test from 'node:test';import assert from 'node:assert/strict';
import {backend} from './api-harness.mjs';
const player=(name,city='Shenyang',place='night')=>({name,city,place,color:'#18776d',skin:'#8b5c43',hair:'cropped',x:0,z:2});
async function setup(){const t=backend();for(const id of ['alice','bob','eve']){await t.call(id,'/api/presence','POST',player(id));t[id]=(await(await t.call(id,'/api/account')).json()).id}return t}
const venue={channel:'venue',city:'Shenyang',place:'night'};
const path='/api/messages?channel=venue&city=Shenyang&place=night';
async function befriend(t){assert.equal((await t.call('alice','/api/friends','POST',{peer:t.bob,action:'request'})).status,200);assert.equal((await t.call('bob','/api/friends','POST',{peer:t.alice,action:'accept'})).status,200)}
test('presence and venue messages are isolated by city and venue',async()=>{const t=await setup();await t.call('bob','/api/presence','POST',player('bob','Guangzhou'));let response=await t.call('alice','/api/presence','POST',player('alice'));assert.equal((await response.json()).players.length,1);assert.equal((await t.call('alice','/api/messages','POST',{...venue,text:'Hello Shenyang'})).status,200);assert.equal((await t.call('bob',path)).status,403);assert.equal((await(await t.call('bob','/api/messages?channel=venue&city=Guangzhou&place=night')).json()).messages.length,0);assert.equal((await t.call(null,path)).status,401);t.sqlite.prepare("UPDATE city_presence SET seen_at = 0 WHERE user_id = 'alice'").run();assert.equal((await t.call('alice',path)).status,403)});
test('friend acceptance and private-message authorization cannot be bypassed',async()=>{const t=await setup();const dm='/api/messages?channel=direct&peer='+t.bob;assert.equal((await t.call('alice',dm)).status,403);await t.call('alice','/api/friends','POST',{peer:t.bob,action:'request'});assert.equal((await t.call('alice','/api/friends','POST',{peer:t.bob,action:'accept'})).status,403);assert.equal((await t.call('eve','/api/friends','POST',{peer:t.bob,action:'accept'})).status,403);await t.call('bob','/api/friends','POST',{peer:t.alice,action:'accept'});const sent=await t.call('alice','/api/messages','POST',{channel:'direct',peer:t.bob,text:'Private hello'});assert.equal(sent.status,200);const key=(await sent.json()).id;const messages=(await(await t.call('bob','/api/messages?channel=direct&peer='+t.alice)).json()).messages;assert.equal(messages[0].body,'Private hello');assert.equal('sender_id' in messages[0],false);assert.equal('email' in messages[0],false);assert.equal((await t.call('eve','/api/messages?channel=direct&peer='+t.alice)).status,403);assert.equal((await t.call('bob','/api/messages?id='+key,'DELETE')).status,403);assert.equal((await t.call('alice','/api/messages?id='+key,'DELETE')).status,200)});
test('blocking hides avatars and messages and closes private messaging in both directions',async()=>{const t=await setup();await befriend(t);await t.call('bob','/api/messages','POST',{...venue,text:'A message'});await t.call('alice','/api/block','POST',{peer:t.bob,blocked:true});assert.equal((await(await t.call('alice',path)).json()).messages.length,0);const peers=(await(await t.call('bob','/api/presence','POST',player('bob'))).json()).players;assert.ok(!peers.some(p=>p.id===t.alice));assert.equal((await t.call('bob','/api/messages','POST',{channel:'direct',peer:t.alice,text:'Blocked message'})).status,403);assert.equal((await(await t.call('alice','/api/social')).json()).friends.length,0);assert.equal((await(await t.call('alice','/api/social')).json()).blocked.length,1);await t.call('alice','/api/block','POST',{peer:t.bob,blocked:false});assert.equal((await(await t.call('alice','/api/social')).json()).blocked.length,0)});
test('reports require message visibility and are deduplicated',async()=>{const t=await setup();const key=(await(await t.call('bob','/api/messages','POST',{...venue,text:'Reportable message'})).json()).id;for(let i=0;i<2;i++)assert.equal((await t.call('alice','/api/report','POST',{message:key,reason:'spam'})).status,200);assert.equal(t.sqlite.prepare('SELECT count(*) AS n FROM chat_reports').get().n,1);await t.call('eve','/api/presence','POST',player('eve','Beijing'));assert.equal((await t.call('eve','/api/report','POST',{message:key,reason:'spam'})).status,403);await befriend(t);const dm=(await(await t.call('bob','/api/messages','POST',{channel:'direct',peer:t.alice,text:'Private'})).json()).id;assert.equal((await t.call('eve','/api/report','POST',{message:dm,reason:'spam'})).status,404)});
test('message limits reject invalid text and throttle repeated sending',async()=>{const t=await setup();for(const text of ['', 'x'.repeat(401)])assert.equal((await t.call('alice','/api/messages','POST',{...venue,text})).status,400);for(let i=0;i<5;i++)assert.equal((await t.call('alice','/api/messages','POST',{...venue,text:'Message '+i})).status,200);assert.equal((await t.call('alice','/api/messages','POST',{...venue,text:'Too many'})).status,429)});
test('leaving multiplayer preserves a player profile and accepted private conversations',async()=>{const t=await setup();await befriend(t);await t.call('bob','/api/presence','DELETE');assert.equal((await t.call('bob',path)).status,403);assert.equal((await t.call('bob','/api/messages','POST',{channel:'direct',peer:t.alice,text:'I am offline in the world'})).status,200);const peers=(await(await t.call('alice','/api/social')).json()).friends;assert.equal(peers[0].online,false);assert.equal(peers[0].name,'bob')});
