import test from 'node:test';import assert from 'node:assert/strict';import {harness,fixture} from './game-harness.mjs';
function create(start='inside',city='Shenyang',other=false){const t=harness(null);t.document.querySelector('[data-start="'+start+'"]').onclick();t.click('nextStep');t.document.getElementById('onName').oninput({target:{value:'New Student'}});for(let i=0;i<4;i++)t.click('nextStep');t.document.getElementById('studentCity').value=city;if(other){t.document.querySelector('#studentUniversity option[selected]')?.removeAttribute('selected');t.document.querySelector('#studentUniversity option[value="other"]').setAttribute('selected','');t.document.getElementById('studentSchool').value='My University'}t.click('nextStep');assert.equal(t.game.state.created,true);return t}
test('inside-China students retain their university and arrive at the first chapter',()=>{const t=create();assert.equal(t.game.state.background,'Student');assert.equal(t.game.state.student.university,'Northeastern University');assert.equal(t.game.state.story.phase,'arrival');assert.equal(t.game.state.place,'campus');assert.match(t.document.getElementById('activityContent').textContent,/University welcome desk/);const restored=harness(JSON.parse(JSON.stringify(t.game.state)));assert.deepEqual(JSON.parse(JSON.stringify(restored.game.state.student)),JSON.parse(JSON.stringify(t.game.state.student)))});
test('overseas journey is sequential, duplicate safe and converges on China arrival',()=>{const t=create('outside');assert.equal(t.game.state.story.phase,'preparation');const old=t.document.getElementById('storyNext').onclick;old();old();assert.equal(t.game.state.story.index,1);for(let i=1;i<6;i++)t.click('storyNext');assert.equal(t.game.state.story.phase,'arrival');assert.equal(t.game.state.story.index,0);assert.equal(t.game.state.place,'airport');assert.equal(t.game.state.student.start,'outside')});
test('unsupported profile remains accurate and explicitly uses a temporary campus',()=>{const t=create('inside','Wuhan',true);assert.equal(t.game.state.student.studyCity,'Wuhan');assert.equal(t.game.state.student.university,'My University');assert.equal(t.game.state.student.temporary,true);assert.equal(t.game.state.city,'Shenyang');assert.match(t.document.getElementById('activityContent').textContent,/temporary Shenyang campus/)});
test('arrival chapters require venues and preserve progression',()=>{const t=create();assert.equal(t.game.state.story.index,1);t.click('storyNext');t.game.state.place='home';t.game.studentStory();t.click('storyNext');t.game.state.place='mall';t.game.studentStory();const money=t.game.state.money;t.click('storyNext');assert.equal(t.game.state.money,money);assert.equal(t.game.state.story.index,4);const restored=harness(JSON.parse(JSON.stringify(t.game.state)));assert.equal(restored.game.state.story.index,4);assert.throws(()=>restored.game.loadSave({...restored.game.state,story:{phase:'arrival',index:999}}));assert.equal(harness(fixture()).game.state.student,undefined)});

test('existing students opt into the introduction without recreating their character',()=>{const t=harness({...fixture(),money:9000,xp:300,upgrades:['bed']});t.game.studentStory();t.click('startStudentIntro');t.click('nextStep');assert.equal(t.game.state.name,'Tester');assert.equal(t.game.state.money,9000);assert.equal(t.game.state.xp,300);assert.ok(t.game.state.upgrades.includes('bed'));assert.equal(t.game.state.story.phase,'arrival');assert.equal(t.game.state.story.index,1)});

test('stale story callbacks cannot advance a restored account character',()=>{const t=create();const old=t.document.getElementById('storyNext').onclick;t.game.loadSave(JSON.parse(JSON.stringify(t.game.state)));old();assert.equal(t.game.state.story.index,1)});
