import test from 'node:test';import assert from 'node:assert/strict';import {harness,fixture} from './game-harness.mjs';
function create(start='inside',role='Student'){const t=harness(null);t.document.querySelector('[data-start="'+start+'"]').onclick();t.click('nextStep');t.document.querySelector('[data-role="'+role+'"]').onclick();t.click('nextStep');t.document.getElementById('onName').oninput({target:{value:'New Student'}});t.click('nextStep');assert.equal(t.game.state.created,true);return t}
test('setup asks the starting point, role and character look, then opens no story pop-up',()=>{const t=harness(null);t.document.querySelector('[data-start="outside"]').onclick();t.click('nextStep');t.document.querySelector('[data-role="Student"]').onclick();t.click('nextStep');t.document.getElementById('onName').oninput({target:{value:'Ada'}});t.document.querySelector('[data-skin="#603c2c"]').onclick();t.document.querySelector('[data-hair="bun"]').onclick();t.document.querySelector('[data-color="#4e8c9a"]').onclick();t.click('nextStep');assert.equal(t.game.state.name,'Ada');assert.equal(t.game.state.appearance.skin,'#603c2c');assert.equal(t.game.state.appearance.hair,'bun');assert.equal(t.game.state.color,'#4e8c9a');assert.equal(t.game.state.student.start,'outside');assert.equal(t.game.state.place,'airport');assert.equal(t.game.state.city,'Shenyang');assert.equal(t.game.state.story.phase,'arrival');assert.equal(t.document.getElementById('activityDialog').open,false)});
test('inside-China students keep their university and start at the campus task',()=>{const t=create();assert.equal(t.game.state.background,'Student');assert.equal(t.game.state.student.university,'Northeastern University');assert.equal(t.game.state.story.index,1);assert.equal(t.game.state.place,'campus');t.game.studentStory();assert.match(t.document.getElementById('activityContent').textContent,/University welcome desk/);const restored=harness(JSON.parse(JSON.stringify(t.game.state)));assert.deepEqual(JSON.parse(JSON.stringify(restored.game.state.student)),JSON.parse(JSON.stringify(t.game.state.student)))});
test('every role starts in Shenyang with its own money, skill and phone',()=>{
 for(const [role,money,skill,first] of [['Student',3200,'Study','Student story'],['Entrepreneur',8000,'Network','My business'],['Worker',3200,'Digital','Career'],['Creator',3200,'Creativity','Studio'],['Tourist',6000,'Social','Trips']]){
  const t=create('inside',role);assert.equal(t.game.state.background,role);assert.equal(t.game.state.money,money);assert.equal(t.game.state.skills[skill],2);assert.equal(t.game.state.city,'Shenyang');assert.equal(Boolean(t.game.state.student),role==='Student');
  t.game.phone();const apps=[...t.document.querySelectorAll('#phoneContent .phone-app span')].map(x=>x.textContent);assert.equal(apps[0],first);assert.equal(apps.includes('Student story'),role==='Student');assert.equal(apps.includes('Jobs')||apps.includes('Career')||apps.includes('Part-time jobs'),role!=='Tourist');
  assert.equal(harness(JSON.parse(JSON.stringify(t.game.state))).game.state.background,role);
 }
});
test('older saves still preparing to leave continue at the arrival tasks',()=>{const old={...fixture(),student:{start:'outside',path:'study',country:'Nigeria',departure:'Lagos',studyCity:'Shenyang',university:'Northeastern University',studyLevel:'Undergraduate',major:'',campus:'campus',temporary:false},story:{version:1,phase:'preparation',index:3,season:'winter'},background:'Student'};const t=harness(old);assert.equal(t.game.state.story.phase,'arrival');assert.equal(t.game.state.story.index,0)});
test('arrival tasks require venues and preserve progression',()=>{const t=create();t.game.studentStory();assert.equal(t.game.state.story.index,1);t.click('storyNext');t.game.state.place='home';t.game.studentStory();t.click('storyNext');t.game.state.place='mall';t.game.studentStory();const money=t.game.state.money;t.click('storyNext');assert.equal(t.game.state.money,money);assert.equal(t.game.state.story.index,4);const restored=harness(JSON.parse(JSON.stringify(t.game.state)));assert.equal(restored.game.state.story.index,4);assert.throws(()=>restored.game.loadSave({...restored.game.state,story:{phase:'arrival',index:999}}));assert.equal(harness(fixture()).game.state.student,undefined)});

test('existing students opt into the introduction without recreating their character',()=>{const t=harness({...fixture(),money:9000,xp:300,upgrades:['bed']});t.game.studentStory();t.click('startStudentIntro');t.click('nextStep');assert.equal(t.game.state.name,'Tester');assert.equal(t.game.state.money,9000);assert.equal(t.game.state.xp,300);assert.ok(t.game.state.upgrades.includes('bed'));assert.equal(t.game.state.story.phase,'arrival');assert.equal(t.game.state.story.index,1)});

test('stale story callbacks cannot advance a restored account character',()=>{const t=create();t.game.studentStory();const old=t.document.getElementById('storyNext').onclick;t.game.loadSave(JSON.parse(JSON.stringify(t.game.state)));old();assert.equal(t.game.state.story.index,1)});

test('older empty study level restores without losing student progress',()=>{const t=create();const old=JSON.parse(JSON.stringify(t.game.state));old.student.studyLevel='';old.money='3200';t.game.loadSave(old);assert.equal(t.game.state.student.studyLevel,'Undergraduate');assert.equal(t.game.state.money,3200);assert.equal(t.game.state.story.index,1)});
