import {connectClient} from './hafrik-worker-harness.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {webcrypto} from 'node:crypto';import {harness,fixture} from './game-harness.mjs';import {backend} from './api-harness.mjs';
async function setup(server,id,{deny=false}={}){const t=harness({...fixture(),name:id,place:'night'}),c=t.context,track={enabled:true,stopped:false,stop(){this.stopped=true}};c.crypto=webcrypto;c.URLSearchParams=URLSearchParams;c.fetch=(path,options)=>server.call(id,path,options.method,options.body?JSON.parse(options.body):undefined);let requested=0;c.navigator={mediaDevices:{async getUserMedia(){requested++;if(deny)throw Object.assign(Error('Denied'),{name:'NotAllowedError'});return {getTracks:()=>[track],getAudioTracks:()=>[track]}}}};c.voiceConnections=[];class PC{constructor(){c.voiceConnections.push(this);this.connectionState='new';this.remoteDescription=null;this.localDescription=null;this.closed=false}addTrack(t){(this.senders||=[]).push({track:t,async replaceTrack(n){this.track=n}})}getSenders(){return this.senders||[]}async createOffer(){return {type:'offer',sdp:'mock-offer'}}async createAnswer(){return {type:'answer',sdp:'mock-answer'}}async setLocalDescription(v){this.localDescription=v}async setRemoteDescription(v){this.remoteDescription=v}async addIceCandidate(){}close(){this.closed=true;this.connectionState='closed'}}c.RTCPeerConnection=PC;const silent={kind:'audio',enabled:true,stopped:false,stop(){this.stopped=true}};c.silentTrack=silent;c.AudioContext=class{createMediaStreamDestination(){return {stream:{getTracks:()=>[silent],getAudioTracks:()=>[silent]}}}};await connectClient(t,server,id);await vm.runInContext('(async()=>{'+fs.readFileSync('public/voice.js','utf8')+'})()',c);return {...t,track,get requested(){return requested}}}
test('voice only asks on opt-in, starts talking, exchanges signals, and stops on venue change',async()=>{const server=backend(),a=await setup(server,'alice'),b=await setup(server,'bob');assert.equal(a.requested,0);a.context.ChinaLifeVoice.open();assert.equal(a.requested,0);await a.context.ChinaLifeVoice.join();assert.equal(a.track.enabled,true);assert.equal(a.context.ChinaLifeVoice.active,true,a.document.getElementById('voiceFeedback').textContent);await b.context.ChinaLifeVoice.join();for(let i=0;i<3;i++){await a.context.ChinaLifeVoice.pulse();await b.context.ChinaLifeVoice.pulse()}assert.equal(a.context.ChinaLifeVoice.peers,1);assert.equal(b.context.ChinaLifeVoice.peers,1);a.document.getElementById('voiceMute').onclick();assert.equal(a.track.enabled,false);a.game.state.place='church';a.internal.render();assert.equal(a.context.ChinaLifeVoice.active,false);assert.equal(a.track.stopped,true);assert.equal(a.context.ChinaLifeVoice.peers,0)});
test('denied microphone permission leaves voice off',async()=>{const t=await setup(backend(),'alice',{deny:true});t.context.ChinaLifeVoice.open();await t.context.ChinaLifeVoice.join();assert.equal(t.context.ChinaLifeVoice.active,false);assert.match(t.document.getElementById('voiceFeedback').textContent,/permission was denied/)});
test('backgrounding switches off microphone and closes peer connections',async()=>{const t=await setup(backend(),'alice');await t.context.ChinaLifeVoice.join();t.document.hidden=true;t.document.dispatchEvent(new t.context.Event('visibilitychange'));assert.equal(t.track.stopped,true);assert.equal(t.context.ChinaLifeVoice.active,false)});
test('one join enables talking and speaker recovery appears only when playback is blocked',async()=>{const server=backend(),a=await setup(server,'alice'),b=await setup(server,'bob');a.context.ChinaLifeVoice.open();assert.equal(a.document.getElementById('voiceSpeaker').hidden,true);assert.doesNotMatch(a.document.getElementById('voiceContent').textContent,/Experimental|TURN relay/);await a.document.getElementById('voiceJoin').onclick();await b.context.ChinaLifeVoice.join();await a.context.ChinaLifeVoice.pulse();let blocked=true;const create=a.document.createElement.bind(a.document);a.document.createElement=tag=>{const el=create(tag);if(tag==='audio')el.play=()=>blocked?Promise.reject(Error('Autoplay blocked')):Promise.resolve();return el};a.context.voiceConnections[0].ontrack({streams:[{}]});await new Promise(r=>setImmediate(r));assert.equal(a.document.getElementById('voiceSpeaker').hidden,false);blocked=false;await a.document.getElementById('voiceSpeaker').onclick();assert.equal(a.document.getElementById('voiceSpeaker').hidden,true);assert.equal(a.track.enabled,true);a.document.getElementById('voiceMute').onclick();assert.equal(a.track.enabled,false);await a.document.getElementById('voiceLeave').onclick();assert.equal(a.track.stopped,true)});
test('leaving during microphone permission stops a late stream without joining',async()=>{const t=await setup(backend(),'alice');let resolve;t.context.navigator.mediaDevices.getUserMedia=()=>new Promise(r=>resolve=r);const pending=t.context.ChinaLifeVoice.join();await t.context.ChinaLifeVoice.leave();resolve({getTracks:()=>[t.track],getAudioTracks:()=>[t.track]});await pending;assert.equal(t.track.stopped,true);assert.equal(t.context.ChinaLifeVoice.active,false)});

test('push to talk only sends while held, the LIVE pill follows the mic, and per-player mute is remembered',async()=>{
 const server=backend(),a=await setup(server,'alice'),b=await setup(server,'bob');
 a.context.ChinaLifeVoice.open();await a.context.ChinaLifeVoice.join();await b.context.ChinaLifeVoice.join();
 const live=()=>a.document.getElementById('micLive');assert.equal(a.track.enabled,true);assert.equal(live().hidden,false);
 a.context.ChinaLifeVoice.open();const ptt=a.document.getElementById('voicePtt');ptt.checked=true;ptt.onchange({target:ptt});assert.equal(a.track.enabled,false);assert.equal(live().hidden,true);
 const talk=a.document.getElementById('voiceTalk'),ev={preventDefault(){}};talk.onpointerdown(ev);assert.equal(a.track.enabled,true);assert.equal(live().hidden,false);talk.onpointerup(ev);assert.equal(a.track.enabled,false);
 for(let i=0;i<3;i++){await a.context.ChinaLifeVoice.pulse();await b.context.ChinaLifeVoice.pulse()}a.context.ChinaLifeVoice.open();
 const mute=a.document.querySelector('[data-voice-mute]');assert.ok(mute,'mute button for the other player');mute.onclick();assert.equal(a.context.ChinaLifeVoice.prefs.mutedPeers.length,1);
 await a.context.ChinaLifeVoice.leave();assert.equal(live().hidden,true);
});

test('on-screen microphone joins and toggles mute without opening a dialog',async()=>{const t=await setup(backend(),'alice');const b=t.document.getElementById('quickVoice');assert.equal(t.document.getElementById('voiceDialog').open,false);await b.onclick();assert.equal(t.context.ChinaLifeVoice.active,true);assert.equal(t.track.enabled,true);await b.onclick();assert.equal(t.track.enabled,false);assert.equal(b.getAttribute('aria-label'),'Unmute microphone');await b.onclick();assert.equal(t.track.enabled,true);assert.equal(t.document.getElementById('voiceDialog').open,false);await t.context.ChinaLifeVoice.leave();assert.equal(t.track.stopped,true)});
test('speakers join on their own without the microphone, and tapping the mic swaps in the real track',async()=>{const server=backend(),a=await setup(server,'alice'),b=await setup(server,'bob');await a.context.ChinaLifeVoice.join(true);assert.equal(a.requested,0);assert.equal(a.context.ChinaLifeVoice.active,true);assert.equal(a.context.ChinaLifeVoice.listening,true);assert.equal(a.context.ChinaLifeVoice.muted,true);await b.context.ChinaLifeVoice.join();for(let i=0;i<3;i++){await a.context.ChinaLifeVoice.pulse();await b.context.ChinaLifeVoice.pulse()}assert.equal(a.context.ChinaLifeVoice.peers,1);const pc=a.context.voiceConnections.at(-1);assert.equal(pc.getSenders()[0].track,a.context.silentTrack);await a.document.getElementById('quickVoice').onclick();assert.equal(a.requested,1);assert.equal(a.context.ChinaLifeVoice.listening,false);assert.equal(a.context.ChinaLifeVoice.muted,false);assert.equal(pc.getSenders()[0].track,a.track);assert.equal(a.context.silentTrack.stopped,true);assert.equal(a.track.enabled,true)});
test('a dropped voice request does not reset voice, three in a row disconnect, and listening alone never ducks club music',async()=>{const server=backend(),a=await setup(server,'alice'),b=await setup(server,'bob');await a.context.ChinaLifeVoice.join(true);await b.context.ChinaLifeVoice.join();for(let i=0;i<2;i++){await a.context.ChinaLifeVoice.pulse();await b.context.ChinaLifeVoice.pulse()}
 const real=a.context.fetch;let fail=true;a.context.fetch=(path,options)=>fail&&/voice/.test(path)?Promise.reject(Object.assign(TypeError('Failed to fetch'))):real(path,options);
 await a.context.ChinaLifeVoice.pulse();await a.context.ChinaLifeVoice.pulse();assert.equal(a.context.ChinaLifeVoice.active,true,'two blips keep voice on');
 fail=false;await a.context.ChinaLifeVoice.pulse();assert.equal(a.context.ChinaLifeVoice.active,true);
 fail=true;for(let i=0;i<3;i++)await a.context.ChinaLifeVoice.pulse();assert.equal(a.context.ChinaLifeVoice.active,false,'three failures in a row disconnect');
 let events=[];a.context.addEventListener('chinalife:voice',e=>events.push(e.detail.active));fail=false;await a.context.ChinaLifeVoice.join(true);assert.equal(a.context.ChinaLifeVoice.active,true);assert.ok(!events.includes(true),'listening only never ducks the club music');
});
