import {entryPosition,roomPosition} from '../public/presence-layout.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import * as THREE from '../public/vendor/three.module.js';import {buildingModel,interiorModel,furnitureModel,airplaneModel} from '../public/models.js';import {harness} from './game-harness.mjs';import {walkingPath,activityMotion} from '../public/movement.js';import {cityLayout,streetRoute} from '../public/city-layout.js';
function setup(){const t=harness(),{document,context}=t;let frame,time=0;const create=document.createElement.bind(document);document.createElement=(name)=>{const el=create(name);if(name==='canvas'){el.getContext=()=>{const noop=new Proxy(function(){},{get:(t,k)=>k===Symbol.toPrimitive?()=>0:noop,apply:()=>noop,set:()=>true});return noop};el.setPointerCapture=()=>{};el.getBoundingClientRect=()=>({left:0,top:0,width:390,height:844})}return el};const viewport=document.getElementById('worldViewport');Object.defineProperties(viewport,{clientWidth:{value:390},clientHeight:{value:844}});class Renderer{constructor(){this.domElement=document.createElement('canvas');this.shadowMap={}}setSize(){}setPixelRatio(){}render(){}}Object.assign(context,{entryPosition,roomPosition,buildingModel,interiorModel,furnitureModel,airplaneModel,walkingPath,activityMotion,cityLayout,streetRoute});context.THREE={...THREE,WebGLRenderer:Renderer};context.requestAnimationFrame=fn=>frame=fn;vm.runInContext('(function(){'+fs.readFileSync('public/china-city.js','utf8').replace(/^import .*?;\s*/gm,'').replace(/export function /g,'function ')+ ';Object.assign(window,{chineseResidential,chineseCityDetails,chineseVenueDetails});})()',context);vm.runInContext('(function(){'+fs.readFileSync('public/characters.js','utf8').replace(/^import .*?;\s*/gm,'').replace(/export function /g,'function ')+';Object.assign(window,{characterModel,npcLook});})()',context);vm.runInContext('(function(){'+fs.readFileSync('public/district-centre.js','utf8').replace(/^import .*?;\s*/gm,'').replace(/export function /g,'function ').replace(/export const /g,'const ')+';Object.assign(window,{buildCityCentre,centreBlocked,CENTRE});})()',context);vm.runInContext('(function(){'+fs.readFileSync('public/skyline.js','utf8').replace(/^import .*?;\s*/gm,'').replace(/export function /g,'function ')+';Object.assign(window,{skyline,vehicles,moveVehicle,car,jet,airfield});})()',context);vm.runInContext(fs.readFileSync('public/world.js','utf8').replace(/^import .*?;\s*/gm,''),context);assert.ok(context.ChinaLifeWorld,'World initialization');return {...t,world:context.ChinaLifeWorld,tick(seconds=1){for(let i=0;i<20*seconds;i++){time+=50;frame(time)}},key(key){const e=new context.Event('keydown');e.key=key;context.dispatchEvent(e)}}}
test('every venue builds its scene and map routes all locations to travel',()=>{const t=setup();for(const p of t.game.locations){t.game.state.place=p[0];t.world.venue(p[0]);assert.equal(t.world.view,'venue');assert.equal(t.document.getElementById('worldVenueTitle').textContent,p[1]);assert.ok(t.document.getElementById('worldActivities').children.length)}t.world.map();assert.equal(t.world.view,'map');assert.equal(t.document.querySelectorAll('.venue-label').length,t.game.locations.length);const first=t.document.querySelector('.venue-label');first.onclick({stopPropagation(){}});assert.equal(t.document.getElementById('placeSheet').hidden,false,'a tap shows the place first');assert.equal(t.document.getElementById('activityDialog').open,false,'and never travels straight away');t.document.getElementById('placeGo').onclick();assert.equal(t.document.getElementById('activityDialog').open,true)});
test('keyboard movement respects modal dialogs and scene boundaries',()=>{const t=setup();const start=t.world.position.clone();t.document.getElementById('cloudDialog').showModal();t.key('d');t.tick();assert.equal(t.world.position.x,start.x);t.document.getElementById('cloudDialog').close();t.key('d');t.tick();assert.ok(t.world.position.x>start.x);for(let i=0;i<20;i++){t.key('d');t.tick()}assert.ok(t.world.position.x<=6);t.document.getElementById('worldRotate').onclick();t.document.getElementById('worldZoomIn').onclick();t.document.getElementById('worldZoomOut').onclick()});
test('remote character labels appear, disappear and clear on venue changes',()=>{const t=setup();const send=detail=>t.context.dispatchEvent(new t.context.CustomEvent('chinalife:players',{detail}));send([{id:'other',name:'Visitor',color:'#18776d',skin:'#8b5c43',hair:'cap',x:0,z:2}]);assert.equal(t.document.querySelectorAll('.remote').length,1);send([]);assert.equal(t.document.querySelectorAll('.remote').length,0);send([{id:'other',name:'Visitor',color:'#18776d',skin:'#8b5c43',hair:'cap',x:0,z:2}]);t.world.venue('gym');assert.equal(t.document.querySelectorAll('.remote').length,0)});
test('major city maps build and category filters show the requested venues',()=>{const t=setup();for(const name of Object.keys(t.game.cityData)){t.game.state.city=name;t.internal.render();t.world.map();assert.match(t.document.getElementById('worldVenueTitle').textContent,new RegExp(name));assert.equal(t.document.querySelectorAll('.venue-label').length,t.game.locations.length)}t.game.state.city='Shenyang';t.internal.render();t.world.map();const select=filter=>t.document.querySelector('[data-filter="'+filter+'"]').onclick();select('food');assert.equal(t.document.querySelectorAll('.venue-label').length,5);select('faith');assert.equal(t.document.querySelectorAll('.venue-label').length,1);select('social');assert.equal(t.document.querySelectorAll('.venue-label').length,14);select('all');assert.equal(t.document.querySelectorAll('.venue-label').length,t.game.locations.length)});

test('activities walk to a spot, animate, then apply rewards once',()=>{const t=setup(),before=t.game.state.money,stats=t.game.state.stats.activities;t.game.activity('home',1);assert.equal(t.world.busy,true);assert.equal(t.world.action,'cook');assert.equal(t.game.state.money,before);assert.equal(t.document.getElementById('actionStatus').hidden,false);t.game.activity('home',1);t.tick(15);assert.equal(t.world.busy,false);assert.equal(t.game.state.money,before-18);assert.equal(t.game.state.stats.activities,stats+1);assert.equal(t.document.getElementById('actionStatus').hidden,true)});
test('all location actions have reachable walking spots and complete their motion',()=>{const t=setup();for(const p of t.game.locations){for(let i=0;i<p[7].length;i++){t.game.state.place=p[0];t.world.venue(p[0]);let completed=0;const m=activityMotion(p[0],i);assert.equal(t.world.perform({...m,label:p[7][i][0]},()=>completed++),true,p[0]+':'+i);t.tick(20);assert.equal(completed,1,p[0]+':'+i);assert.equal(t.world.busy,false)}}});
test('taxi follows city streets and charges only on arrival, even if a phone panel opens',()=>{const t=setup(),before=t.game.state.money;t.game.travel('night');t.document.getElementById('cabTravel').onclick();assert.equal(t.world.view,'map');assert.equal(t.world.busy,true);assert.equal(t.game.state.place,'home');assert.equal(t.game.state.money,before);t.game.wallet();t.tick(12);assert.equal(t.game.state.place,'night');assert.equal(t.game.state.money,before-25);assert.equal(t.world.view,'venue');assert.equal(t.world.busy,false)});
test('cancelling motion gives no reward, skipping finishes it only once',()=>{const t=setup(),before=t.game.state.money;t.game.activity('home',1);t.world.cancel();t.tick(10);assert.equal(t.game.state.money,before);t.game.activity('home',1);t.document.getElementById('actionSkip').onclick();t.document.getElementById('actionSkip').onclick();assert.equal(t.game.state.money,before-18);assert.equal(t.world.busy,false)});
test('reduced motion applies actions without starting a walking sequence',()=>{const t=setup();t.game.state.reduceMotion=true;let completed=0;t.world.perform({kind:'dance',label:'Dance'},()=>completed++);assert.equal(completed,1);assert.equal(t.world.busy,false)});

test('remote avatars retain actual coordinates across rebuilds and map return',()=>{const t=setup();const send=detail=>t.context.dispatchEvent(new t.context.CustomEvent('chinalife:players',{detail}));send([{id:2,name:'Neighbour',city:t.game.state.city,place:t.game.state.place,x:3,z:1,color:'#18776d'}]);assert.equal(t.world.playerIds[0],'2');assert.equal(t.world.remotePositions[0].x,3);t.world.venue(t.game.state.place);assert.equal(t.world.playerIds[0],'2');send([{id:2,name:'Neighbour',city:t.game.state.city,place:t.game.state.place,x:-2,z:2,color:'#18776d'}]);t.tick(2);assert.ok(Math.abs(t.world.remotePositions[0].x+2)<.05);const position=t.world.position.clone();t.world.map();assert.equal(t.world.roomPosition.x,position.x);t.world.venue(t.game.state.place);assert.equal(t.world.playerIds[0],'2');assert.equal(t.world.position.x,position.x);});
test('account entry points are spread across the room',()=>{assert.notDeepEqual(entryPosition('1'),entryPosition('2'));for(let i=0;i<100;i++){const p=entryPosition(String(i));assert.ok(p.x>=-6&&p.x<=6&&p.z<=4.5)}});


test('club wall signs use the city club name and Advertise here billboards appear across map and venues',()=>{
 const t=setup();t.game.state.place='night';t.world.venue('night');assert.ok(t.world.signs.includes('007 Club'));assert.equal(t.document.querySelectorAll('.ad-label').length,1);
 t.game.state.city='Guangzhou';t.internal.render();t.world.venue('night');assert.ok(t.world.signs.includes('True Color Club'));
 t.world.map();assert.equal(t.document.querySelectorAll('.ad-label').length,3);assert.ok([...t.document.querySelectorAll('.ad-label')].every(l=>/Advertise here/.test(l.textContent)));
 t.world.venue('home');assert.equal(t.document.querySelectorAll('.ad-label').length,0);
});

test('boarding a flight takes off on the map, switches city mid-air and lands at the destination airport',()=>{
 const t=setup();t.game.state.money=100000;t.game.state.place='airport';t.internal.render();t.game.flights();const names=Object.keys(t.game.cityData).filter(c=>c!=='Shenyang');t.click('flight-'+names.indexOf('Harbin'));
 t.document.querySelector('[data-board]').onclick();assert.equal(t.world.action,'flight');assert.equal(t.world.view,'map');assert.equal(t.game.state.city,'Shenyang');
 t.tick(4.5);assert.equal(t.game.state.city,'Harbin');assert.equal(t.world.action,'flight');
 t.tick(4);assert.equal(t.world.busy,false);assert.equal(t.game.state.city,'Harbin');assert.equal(t.game.state.place,'airport');assert.equal(t.world.view,'venue');assert.equal(t.game.state.flightBookings[0].status,'flown');
});
test('scenic flight circles the city and lands back at the same airport',()=>{
 const t=setup();t.game.state.money=1000;t.game.state.place='airport';t.internal.render();t.game.flights();t.click('scenicFlight');assert.equal(t.world.action,'flight');t.tick(15);assert.equal(t.world.busy,false);assert.equal(t.game.state.city,'Shenyang');assert.equal(t.game.state.money,820+1000);assert.ok(t.game.state.secrets.includes('jet-setter'));
});

test('BLOOD & EMBERS and the SKYLIGHT rooftop are Shenyang clubs with a DJ booth',()=>{
 const t=setup();for(const id of ['blood','skylight']){t.game.state.place=id;t.internal.render();t.world.venue(id);assert.ok(t.game.clubs.includes(id));assert.ok([...t.document.querySelectorAll('.scene-label')].some(l=>/DJ booth/.test(l.textContent)))}
 assert.equal(t.game.locations.find(p=>p[0]==='blood')[1],'BLOOD & EMBERS');assert.equal(t.game.locations.find(p=>p[0]==='skylight')[1],'SKYLIGHT · Rooftop');
});

test('daily red envelopes appear in their venue, pay once and unlock Treasure Hunter after ten',()=>{
 const t=setup(),hunt=t.game.huntSummary();assert.equal(hunt.total,3);assert.equal(hunt.hints.length,3);
 const first=Object.keys(t.game.cityData).length&&['market','cafe','african','hotel','night','blood','skylight','campus','university','liaoning','dongbei','ef','academy','gym','park','mall','plaza','church','business','station','airport'].find(id=>t.game.treasureHere(id));
 t.game.state.place=first;t.internal.render();t.world.venue(first);const tag=[...t.document.querySelectorAll('.scene-label.treasure')];assert.equal(tag.length,1);
 const money=t.game.state.money;tag[0].onclick({stopPropagation(){}});assert.ok(t.game.state.money>money);assert.equal(t.game.huntSummary().found,1);assert.equal(t.game.treasureHere(first),null);
 assert.equal(t.game.collectTreasure(first),false);t.world.venue(first);assert.equal(t.document.querySelectorAll('.scene-label.treasure').length,0);
 t.game.state.treasureTotal=9;const other=['market','cafe','african','hotel','night','blood','skylight','campus','university','liaoning','dongbei','ef','academy','gym','park','mall','plaza','church','business','station','airport'].find(id=>t.game.treasureHere(id));t.game.state.place=other;t.game.collectTreasure(other);assert.ok(t.game.state.secrets.includes('treasure-hunter'));
 const saved=JSON.parse(JSON.stringify(t.game.state));t.game.loadSave(saved);assert.equal(t.game.huntSummary().found,2);assert.ok(t.game.state.secrets.includes('treasure-hunter'));
});

test('live events show in the venue panel, on the map and on billboards, and the admin app is admin-only',()=>{
 const t=setup();t.game.phone();assert.equal(t.document.querySelector('[data-phone="admin"]'),null);
 t.context.ChinaLifeCloud={isAdmin:true,events:[{id:'5',title:'Afrobeats Night',body:'',place:'blood',reward:700,billboard:true,link:'',joined:false,ends_at:Date.now()+36e5}],joinEvent:async()=>{},players:[],cityPlayers:[]};
 t.game.state.place='blood';t.internal.render();t.world.venue('blood');assert.ok([...t.document.querySelectorAll('#worldActivities button')].some(b=>/Afrobeats Night/.test(b.textContent)));
 t.world.map();assert.ok(t.document.querySelector('.venue-label.has-event'));assert.ok([...t.document.querySelectorAll('.ad-label')].every(l=>/Afrobeats Night/.test(l.textContent)));
 t.game.phone();assert.ok(t.document.querySelector('[data-phone="admin"]'));
});

test('both shift buttons start and finish work at every workplace',()=>{for(const style of ['steady','focus'])for(const [job,place] of [['cafe-job','cafe'],['teacher','ef'],['content','business'],['designer','business'],['sales','mall'],['coach','gym'],['delivery','market'],['translator','business']]){const t=setup(),s=t.game.state;s.job=job;s.place=place;s.day=2;s.jobStart=2;s.needs.energy=100;s.needs.hunger=100;t.world.venue(place);t.internal.shiftScreen();const before=s.money;t.click(style==='steady'?'steadyShift':'focusShift');assert.equal(t.world.busy,true,job+':'+style);assert.equal(s.money,before);t.tick(20);assert.equal(s.shifts,1,job+':'+style);assert.ok(s.money>before,job+':'+style);assert.equal(t.world.busy,false)}});

test('unavailable shifts explain the reason inside the open shift window',()=>{for(const [change,reason] of [[s=>s.jobStart=3,/starts tomorrow/],[s=>s.lastShift=2,/already worked/],[s=>s.needs.energy=10,/35 energy/],[s=>s.needs.hunger=10,/25 hunger/]]){const t=setup(),s=t.game.state;s.job='cafe-job';s.place='cafe';s.day=2;s.jobStart=1;change(s);t.world.venue('cafe');t.internal.shiftScreen();const before=s.money;assert.match(t.document.getElementById('shiftStatus').textContent,reason);for(const id of ['steadyShift','focusShift']){t.click(id);assert.match(t.document.getElementById('shiftStatus').textContent,reason);assert.equal(t.document.getElementById('activityDialog').open,true);assert.equal(t.world.busy,false);assert.equal(s.money,before)}}});

test('nearby players display saved XP ranks and update without replacing avatars',()=>{const t=setup();const send=(xp,name='Neighbour')=>t.context.dispatchEvent(new t.context.CustomEvent('chinalife:players',{detail:[{id:'2',name,city:t.game.state.city,place:t.game.state.place,x:1,z:2,xp}]}));for(const [xp,rank] of [[0,'Newcomer'],[200,'Explorer'],[600,'Local'],[12000,'Legend']]){send(xp);assert.match(t.document.querySelector('.remote .player-rank').textContent,new RegExp(rank));assert.equal(t.document.querySelectorAll('.remote').length,1)}send(200,'<b>Player</b>');assert.equal(t.document.querySelector('.remote span').textContent,'<b>Player</b>');assert.equal(t.document.querySelector('.remote b'),null);t.world.map();t.world.venue(t.game.state.place);assert.match(t.document.querySelector('.remote .player-rank').textContent,/Explorer/)});

test('all fifteen university campuses and new dining/clubs have separate routes and playable scenes',()=>{const t=setup(),layout=cityLayout('Shenyang',t.game.cityContent);assert.equal(t.game.universityIds.length,15);const positions=new Set();for(const s of t.game.cityContent.universities){assert.equal(t.game.locations.find(p=>p[0]===s.id)[1],s.name);const key=layout.positions[s.id].join(',');assert.equal(positions.has(key),false);positions.add(key);assert.ok(streetRoute(layout,'home',s.id).length);t.game.state.place=s.id;t.world.venue(s.id)}for(const v of [...t.game.cityContent.clubs,...t.game.cityContent.restaurants]){assert.ok(streetRoute(layout,'home',v.id).length);t.game.state.place=v.id;t.world.venue(v.id);assert.ok(t.world.signs.includes(v.name),v.name)}assert.equal(new Set(t.game.cityContent.clubs.map(c=>c.style)).size,9)});
test('all seven travel choices charge once on arrival and cancellation costs nothing',()=>{for(const [id,fare] of [['walkTravel',0],['bikeTravel',2],['metroTravel',4],['busTravel',2],['cabTravel',25],['didiEconomyTravel',18],['didiPremiumTravel',38]]){const t=setup();t.game.state.needs.energy=100;const before=t.game.state.money;t.game.travel('black-sheep');t.click(id);assert.equal(t.game.state.money,before);t.world.cancel();t.tick(15);assert.equal(t.game.state.place,'home');assert.equal(t.game.state.money,before);t.game.travel('black-sheep');t.click(id);t.tick(20);assert.equal(t.game.state.place,'black-sheep',id);assert.equal(t.game.state.money,before-fare,id)}});

test('remote players retain their positions in the expanded 007 room',()=>{const t=setup();t.game.state.place='night';t.world.venue('night');t.context.dispatchEvent(new t.context.CustomEvent('chinalife:players',{detail:[{id:'2',name:'Partner',city:'Shenyang',place:'night',x:7.5,z:5.5,xp:200}]}));assert.equal(t.world.remotePositions[0].x,7.5);assert.equal(t.world.remotePositions[0].z,5.5)});
test('owned homes change interior style, render every purchased item and keep actions reachable',()=>{const t=setup();t.game.state.upgrades=t.game.catalog.furniture.map(f=>f.id);for(const type of ['apartment','townhouse','villa','penthouse','mansion']){t.game.state.properties.Shenyang=type;t.world.venue('home');assert.equal(t.world.homeStyle,type);for(const id of t.game.state.upgrades)assert.ok(t.world.furniture.includes(id),type+':'+id);let completed=0;t.world.perform({...activityMotion('home',1),label:'Cook'},()=>completed++);t.tick(20);assert.equal(completed,1,type)} });
test('switching city addresses and owned home types immediately changes the active house scene',()=>{const t=setup();t.game.state.money=5000000;for(const [id,type] of [['home-mansion','mansion'],['home-nanhu','townhouse']]){t.game.estate(id);t.document.getElementById('estateBuy').onclick();assert.equal(t.game.state.place,id);assert.equal(t.world.homeStyle,type)}t.game.shop('properties','penthouse');t.document.getElementById('shopBuy').onclick();assert.equal(t.game.state.place,'home');assert.equal(t.world.homeStyle,'penthouse');t.game.estate('home-mansion');const money=t.game.state.money;t.document.getElementById('estateBuy').onclick();assert.equal(t.game.state.money,money);assert.equal(t.world.homeStyle,'mansion');assert.equal(t.game.homeAddress(),'home-mansion')});
test('Home navigation from the map travels to the selected owned address',()=>{const t=setup();t.game.state.ownedHomes=['home-mansion'];t.game.state.activeHome='home-mansion';t.game.state.place='plaza';t.world.map();t.document.getElementById('navHome').onclick();t.document.getElementById('choose-home-0').onclick();assert.ok(t.document.getElementById('cabTravel'));t.document.getElementById('cabTravel').onclick();t.tick(12);assert.equal(t.game.state.place,'home-mansion');assert.equal(t.world.homeStyle,'mansion')});

test('Guangzhou has its own landmarks and real names, and Shenyang-only places stay in Shenyang',()=>{
 const t=setup();t.game.state.city='Guangzhou';t.game.state.place='home';t.internal.render();
 const ids=t.game.locations.map(p=>p[0]);for(const id of ['cantontower','cantonfair','baima','consulates','hospital','shamian','beijingroad','kama','partypier','bingsheng','bosphorus','gdufs'])assert.ok(ids.includes(id),id);
 for(const id of ['palace','zhongjie','blood','skylight'])assert.ok(!ids.includes(id),id);
 assert.equal(t.game.locations.find(p=>p[0]==='campus')[1],'Sun Yat-sen University');assert.equal(t.game.locations.find(p=>p[0]==='mall')[1],'Taikoo Hui');
 t.world.map();assert.ok([...t.document.querySelectorAll('.venue-label')].some(l=>/Canton Tower/.test(l.dataset.name)));
 for(const id of ['cantontower','cantonfair','consulates','hospital','kama','bingsheng','shamian']){t.game.state.place=id;t.internal.render();t.world.venue(id);assert.equal(t.world.view,'venue')}
 assert.ok(t.game.clubs.includes('kama'));t.game.state.city='Shenyang';t.internal.render();assert.ok(!t.game.locations.some(p=>p[0]==='cantontower'));
});
test('premium houses include richer furnishings without granting inventory or blocking actions',()=>{const t=setup();t.game.state.upgrades=[];for(const type of ['apartment','townhouse','villa','penthouse','mansion']){t.game.state.properties.Shenyang=type;t.world.venue('home');for(const id of t.game.homeInteriors[type].included)assert.ok(t.world.furniture.includes(id),type+':'+id);assert.equal(t.game.state.upgrades.length,0);let done=0;t.world.perform({...activityMotion('home',1),label:'Cook'},()=>done++);t.tick(20);assert.equal(done,1,type)}});
test('studio order animation closes the panel so the player can see their work',()=>{const t=setup();t.game.state.place='business';t.game.state.business={level:1,orders:0,revenue:0,lastOrder:0};t.world.venue('business');t.game.business();t.document.getElementById('businessOrder').onclick();assert.equal(t.document.getElementById('activityDialog').open,false);assert.equal(t.world.busy,true);t.tick(20);assert.equal(t.game.state.business.orders,1);assert.equal(t.world.busy,false)});

test('map search finds places by name and type, highlights the route and travels on Go there',()=>{
 const t=setup();t.world.map();assert.equal(t.document.getElementById('mapSearch').hidden,false);
 const clubs=t.world.search('club');assert.ok(clubs.length>=2);assert.ok(clubs.every(id=>t.game.clubs.includes(id)));
 assert.deepEqual([...t.world.search('Mukden')],['palace']);assert.ok([...t.world.search('univ')].includes('campus'),'type search');
 t.world.showRoute('palace');assert.match(t.document.getElementById('mapSearchResults').textContent,/Mukden Palace/);assert.ok(t.document.querySelector('.scene-label.search-hit'));
 t.document.getElementById('searchGo').onclick();assert.equal(t.document.getElementById('mapSearchResults').textContent,'');
 t.world.venue('home');assert.equal(t.document.getElementById('mapSearch').hidden,true);
});

test('action menu plays looping emotes with props, smoking only where allowed, and walking ends them',()=>{
 const t=setup();t.game.state.place='home';t.internal.render();t.world.venue('home');
 t.document.getElementById('worldEmote').onclick();assert.equal(t.document.getElementById('emotePanel').hidden,false);assert.ok(t.document.querySelectorAll('#emotePanel [data-emote]').length>=10);
 t.document.querySelector('[data-emote="dance"]').onclick();assert.equal(t.world.emoteNow,'dance');t.tick(1);assert.equal(t.world.emoteNow,'dance');
 t.world.emote('smoke');assert.equal(t.world.emoteNow,'dance','no smoking at home');assert.match(t.document.getElementById('toast').textContent,/only allowed/);
 t.world.emote('drink');assert.equal(t.world.emoteNow,'drink');t.world.emote('stop');assert.equal(t.world.emoteNow,null);
 t.game.state.place='night';t.internal.render();t.world.venue('night');t.world.emote('smoke');assert.equal(t.world.emoteNow,'smoke');
 t.world.emote('sit');assert.equal(t.world.emoteNow,'sit');
});

test('buying a house from a public venue routes into the purchased private interior',()=>{
 const t=setup();t.game.state.place='plaza';t.game.state.money=5000000;t.world.venue('plaza');t.game.estate('home-mansion');t.click('estateBuy');const balance=t.game.state.money;assert.equal(t.game.state.place,'plaza');t.click('estateGoHome');t.click('cabTravel');t.tick(20);assert.equal(t.game.state.place,'home-mansion');assert.equal(t.world.homeStyle,'mansion');assert.equal(t.game.state.money,balance-25);assert.equal(t.document.getElementById('activityDialog').open,false);
});

test('private homes render bathroom fixtures, purchased finishes and a fan',()=>{const t=setup();t.game.state.upgrades=['toilet','shower','fan'];t.game.state.furnitureColors.fan='#426dba';t.world.venue('home');for(const id of ['toilet','shower','fan'])assert.ok(t.world.furniture.includes(id),id);assert.ok(t.world.signs.every(s=>!s.includes('Shared')));t.world.map();assert.equal(t.document.getElementById('mapSearch').parentNode,t.document.getElementById('mapFilters').parentNode)});

test('static scenery is merged so the city map stays within a phone-friendly mesh budget',()=>{const t=setup();t.world.map();const map=t.context.ChinaLifeWorld.stats();assert.ok(map.meshes<700,'map meshes '+map.meshes);assert.ok(map.triangles>40000,'scenery is still drawn');t.game.state.place='hq';t.world.venue('hq');const hq=t.context.ChinaLifeWorld.stats();assert.ok(hq.meshes<200,'hq meshes '+hq.meshes);assert.equal(hq.view,'venue')});

test('map labels switch between names, icons and hidden, remember the choice and never overlap',()=>{const t=setup();t.world.map();t.tick();const ui=t.document.getElementById('worldUI'),btn=t.document.getElementById('mapLabelMode');assert.ok(ui.classList.contains('labels-names'));
 const shown=()=>[...t.document.querySelectorAll('.venue-label')].filter(l=>!l.hidden);assert.ok(shown().length>0,'some labels show');
 btn.onclick();assert.ok(ui.classList.contains('labels-icons'));btn.onclick();t.tick();assert.ok(ui.classList.contains('labels-hidden'));assert.equal(shown().length,0,'hidden mode shows no building labels');
 btn.onclick();assert.ok(ui.classList.contains('labels-names'));
 const again=setup();again.world.map();assert.ok(again.document.getElementById('worldUI').classList.contains('labels-names'));
 t.world.map(true);t.tick();const all=t.document.querySelectorAll('.venue-label').length;assert.ok(shown().length<all,'zoomed out, less important or overlapping labels step aside ('+shown().length+'/'+all+')')});

test('browsing another city map never moves the player, and travel is a separate choice',()=>{const t=setup();t.game.setOpenCities(['Guangzhou']);t.world.map();const look=[...t.document.querySelectorAll('#worldActivities button')].find(b=>/Look around Guangzhou/.test(b.textContent));assert.ok(look,'the map panel offers browsing other open cities');
 const place=t.game.state.place;look.click();assert.equal(t.game.state.city,'Shenyang','still in Shenyang');assert.equal(t.game.state.place,place);
 assert.match(t.document.getElementById('worldVenueTitle').textContent,/Guangzhou/);assert.ok([...t.document.querySelectorAll('.venue-label')].some(l=>/Canton Tower/.test(l.dataset.name)),'shows Guangzhou places');
 const tower=[...t.document.querySelectorAll('.venue-label')].find(l=>/Canton Tower/.test(l.dataset.name));tower.onclick({stopPropagation(){}});assert.match(t.document.getElementById('placeGo').textContent,/Travel to Guangzhou/);
 t.document.getElementById('placeGo').onclick();assert.equal(t.game.state.city,'Shenyang','travel opens the flight screen, it does not teleport');assert.equal(t.document.getElementById('activityDialog').open,true);
 t.document.getElementById('activityDialog').close();t.document.getElementById('mapLocate').onclick();assert.match(t.document.getElementById('worldVenueTitle').textContent,/Shenyang/)});

test('two-finger pinch zooms the map and a drag keeps gliding with momentum',()=>{const t=setup();t.context.performance=performance;t.world.map();t.tick();const canvas=t.document.querySelector('#worldViewport canvas'),fire=(type,id,x,y)=>{const e=new t.context.Event(type);Object.assign(e,{pointerId:id,clientX:x,clientY:y,preventDefault(){}});canvas.dispatchEvent(e)};
 assert.equal(t.world.stats().view,'map');
 fire('pointerdown',1,100,300);fire('pointerdown',2,200,300);fire('pointermove',2,300,300);fire('pointerup',2,300,300);fire('pointerup',1,100,300);
 const cam=t.world.cameraScale();assert.ok(cam<42,'spreading two fingers zooms in ('+cam+')');
 fire('pointerdown',3,100,300);for(let i=1;i<=6;i++)fire('pointermove',3,100+i*30,300);fire('pointerup',3,280,300);const a=t.world.focus();t.tick(.5);const b=t.world.focus();assert.ok(Math.hypot(a.x-b.x,a.z-b.z)>0,'the map keeps gliding after release')});

test('the Shenyang City Centre prototype replaces the generic block only in Shenyang and stays within budget',()=>{const t=setup();t.world.map();const sy=t.context.ChinaLifeWorld.stats();assert.ok(sy.meshes<700,'meshes '+sy.meshes);
 const centre=t.context.cityLayout('Shenyang',t.game.cityContent);assert.deepEqual([...centre.positions.hotel],[-6,-9],'the hotel stands behind the square');
 for(const id of ['plaza','hotel','black-sheep'])assert.ok(t.game.locations.some(p=>p[0]===id),id+' keeps its place ID');
 const gz=t.context.cityLayout('Guangzhou',t.game.contentFor('Guangzhou'));assert.deepEqual([...gz.positions.hotel],[-6,10],'Guangzhou is unchanged');
 t.game.setOpenCities(['Guangzhou']);t.world.browse('Guangzhou');assert.match(t.document.getElementById('worldVenueTitle').textContent,/Guangzhou/);assert.ok(t.context.ChinaLifeWorld.stats().meshes<700)});

test('outdoor light follows the game clock, each city has daily weather, and interiors keep their own lighting',()=>{const t=setup(),W=t.context.ChinaLifeWorld;t.game.state.place='plaza';
 const dayOf=want=>{for(let d=1;d<400;d++)if(W.weatherFor('Shenyang',d)===want)return d};t.game.state.day=dayOf('clear');
 t.game.state.hour=13*60;t.world.map();const noon=W.lighting().sun;t.game.state.hour=23*60;t.world.map();const night=W.lighting().sun;assert.ok(noon>2.5&&night<1,'noon '+noon+' night '+night);
 assert.equal(W.weatherFor('Shenyang',5),W.weatherFor('Shenyang',5),'weather is stable for the day');assert.ok(['clear','cloudy','rain','snow'].includes(W.weatherFor('Guangzhou',3)));
 for(let d=1;d<200;d++)assert.notEqual(W.weatherFor('Guangzhou',d),'snow','no snow in Guangzhou');
 t.game.state.day=dayOf('snow');t.game.state.hour=13*60;t.world.map();assert.equal(W.lighting().weather,'snow');
 t.game.state.place='gym';t.world.venue('gym');assert.equal(W.lighting().outdoor,false);assert.equal(W.lighting().weather,'clear','no snow indoors');assert.equal(W.lighting().sun,3)});
