CREATE TABLE IF NOT EXISTS chinalife_saves (
    user_id INT UNSIGNED NOT NULL,
    revision INT UNSIGNED NOT NULL DEFAULT 1,
    character_data LONGTEXT NOT NULL,
    game_state LONGTEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id),
    CONSTRAINT fk_chinalife_saves_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Run this once in the same Hafrik database used by the API.
-- If users.user_id is BIGINT, change INT UNSIGNED references below to BIGINT UNSIGNED.
CREATE TABLE IF NOT EXISTS chinalife_presence (
 user_id INT UNSIGNED NOT NULL PRIMARY KEY,name VARCHAR(100) NOT NULL,city VARCHAR(80) NOT NULL,place VARCHAR(80) NOT NULL,color CHAR(7) NOT NULL DEFAULT '#246fa7',skin CHAR(7) NOT NULL DEFAULT '#8b5c43',hair VARCHAR(12) NOT NULL DEFAULT 'cropped',x DECIMAL(8,2) NOT NULL DEFAULT 0,z DECIMAL(8,2) NOT NULL DEFAULT 0,seen_at DATETIME NOT NULL,
 INDEX idx_chinalife_presence_room(city,place,seen_at),CONSTRAINT fk_chinalife_presence_user FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_messages (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,sender_id INT UNSIGNED NOT NULL,recipient_id INT UNSIGNED NULL,city VARCHAR(80) NOT NULL,place VARCHAR(80) NOT NULL,body VARCHAR(400) NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_chinalife_messages_room(city,place,created_at),INDEX idx_chinalife_messages_direct(sender_id,recipient_id,created_at),CONSTRAINT fk_chinalife_messages_sender FOREIGN KEY(sender_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_voice_members (
 user_id INT UNSIGNED NOT NULL PRIMARY KEY,session VARCHAR(80) NOT NULL,city VARCHAR(80) NOT NULL,place VARCHAR(80) NOT NULL,muted TINYINT(1) NOT NULL DEFAULT 1,seen_at DATETIME NOT NULL,
 INDEX idx_chinalife_voice_room(city,place,seen_at),CONSTRAINT fk_chinalife_voice_user FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_voice_signals (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,sender_id INT UNSIGNED NOT NULL,sender_session VARCHAR(80) NOT NULL,target_id INT UNSIGNED NOT NULL,city VARCHAR(80) NOT NULL,place VARCHAR(80) NOT NULL,target_session VARCHAR(80) NOT NULL,payload TEXT NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_chinalife_voice_signals_target(target_id,target_session,id),CONSTRAINT fk_chinalife_voice_sender FOREIGN KEY(sender_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chinalife_friends (
 first_id INT UNSIGNED NOT NULL,second_id INT UNSIGNED NOT NULL,requested_by INT UNSIGNED NOT NULL,status VARCHAR(12) NOT NULL,created_at DATETIME NOT NULL,
 PRIMARY KEY(first_id,second_id),INDEX(second_id),INDEX(requested_by,status),
 FOREIGN KEY(first_id) REFERENCES users(user_id) ON DELETE CASCADE,FOREIGN KEY(second_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_blocks (
 owner_id INT UNSIGNED NOT NULL,peer_id INT UNSIGNED NOT NULL,PRIMARY KEY(owner_id,peer_id),INDEX(peer_id),
 FOREIGN KEY(owner_id) REFERENCES users(user_id) ON DELETE CASCADE,FOREIGN KEY(peer_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_reports (
 reporter_id INT UNSIGNED NOT NULL,message_id BIGINT UNSIGNED NOT NULL,reason VARCHAR(24) NOT NULL,message_body VARCHAR(400) NOT NULL,sender_id INT UNSIGNED NOT NULL,created_at DATETIME NOT NULL,
 PRIMARY KEY(reporter_id,message_id),INDEX(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_rate_limits (
 user_id INT UNSIGNED NOT NULL,kind VARCHAR(24) NOT NULL,bucket BIGINT UNSIGNED NOT NULL,hits INT UNSIGNED NOT NULL,
 PRIMARY KEY(user_id,kind),FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_voice_rooms (city VARCHAR(80) NOT NULL,place VARCHAR(80) NOT NULL,PRIMARY KEY(city,place)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_music (
 city VARCHAR(80) NOT NULL PRIMARY KEY,track VARCHAR(24) NOT NULL,started_at BIGINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_music_requests (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,city VARCHAR(80) NOT NULL,track VARCHAR(24) NOT NULL,created_at DATETIME NOT NULL,
 INDEX(city,created_at,id),INDEX(user_id),FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chinalife_transfers (
 id VARCHAR(80) NOT NULL,
 sender_id INT UNSIGNED NOT NULL,
 recipient_id INT UNSIGNED NOT NULL,
 amount INT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL,
 PRIMARY KEY(sender_id,id),
 KEY recipient_history(recipient_id,created_at),
 FOREIGN KEY(sender_id) REFERENCES users(user_id) ON DELETE CASCADE,
 FOREIGN KEY(recipient_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_gist_posts (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,city VARCHAR(40) NOT NULL,title VARCHAR(100) NOT NULL,body VARCHAR(600) NOT NULL,link VARCHAR(300) NOT NULL DEFAULT '',active TINYINT(1) NOT NULL DEFAULT 1,starts_at DATETIME NOT NULL,ends_at DATETIME NOT NULL,created_by INT UNSIGNED NOT NULL,created_at DATETIME NOT NULL,INDEX(city,active,ends_at),FOREIGN KEY(created_by) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_events (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,title VARCHAR(80) NOT NULL,body VARCHAR(300) NOT NULL DEFAULT '',city VARCHAR(40) NOT NULL DEFAULT 'Shenyang',place VARCHAR(24) NOT NULL DEFAULT '',
 reward INT UNSIGNED NOT NULL DEFAULT 0,billboard TINYINT(1) NOT NULL DEFAULT 0,link VARCHAR(300) NOT NULL DEFAULT '',starts_at DATETIME NOT NULL,ends_at DATETIME NOT NULL,created_by INT UNSIGNED NOT NULL,created_at DATETIME NOT NULL,
 INDEX(city,ends_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_event_claims (
 event_id INT UNSIGNED NOT NULL,user_id INT UNSIGNED NOT NULL,created_at DATETIME NOT NULL,PRIMARY KEY(event_id,user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_admin_log (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,admin_id INT UNSIGNED NOT NULL,action VARCHAR(40) NOT NULL,target_id INT UNSIGNED NULL,amount BIGINT NULL,note VARCHAR(300) NOT NULL DEFAULT '',created_at DATETIME NOT NULL,INDEX(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_golden (
 week VARCHAR(10) NOT NULL PRIMARY KEY,user_id INT UNSIGNED NOT NULL,created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_settings (
 name VARCHAR(40) NOT NULL PRIMARY KEY,value TEXT NOT NULL,updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_push (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,endpoint VARCHAR(700) NOT NULL,endpoint_hash CHAR(64) NOT NULL,created_at DATETIME NOT NULL,
 UNIQUE KEY(endpoint_hash),INDEX(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_shared_activities (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 inviter_id INT UNSIGNED NOT NULL,invitee_id INT UNSIGNED NOT NULL,
 kind VARCHAR(24) NOT NULL,city VARCHAR(40) NOT NULL,place VARCHAR(24) NOT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'pending',ready_a TINYINT(1) NOT NULL DEFAULT 0,ready_b TINYINT(1) NOT NULL DEFAULT 0,
 choice_a VARCHAR(24) NULL,choice_b VARCHAR(24) NULL,
 created_at DATETIME NOT NULL,expires_at DATETIME NOT NULL,started_at DATETIME NULL,completed_at DATETIME NULL,
 INDEX(inviter_id,status),INDEX(invitee_id,status),INDEX(completed_at),
 FOREIGN KEY(inviter_id) REFERENCES users(user_id) ON DELETE CASCADE,
 FOREIGN KEY(invitee_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_fortune_claims (
 user_id INT UNSIGNED NOT NULL,reward_id VARCHAR(40) NOT NULL,amount INT UNSIGNED NOT NULL,claimed_at DATETIME NOT NULL,
 PRIMARY KEY(user_id,reward_id),FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_player_reports (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,reporter_id INT UNSIGNED NOT NULL,peer_id INT UNSIGNED NOT NULL,reason VARCHAR(24) NOT NULL,note VARCHAR(300) NOT NULL DEFAULT '',city VARCHAR(40) NOT NULL DEFAULT '',place VARCHAR(40) NOT NULL DEFAULT '',created_at DATETIME NOT NULL,
 UNIQUE KEY(reporter_id,peer_id,reason),INDEX(created_at),INDEX(peer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_home_visits (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,owner_id INT UNSIGNED NOT NULL,guest_id INT UNSIGNED NOT NULL,city VARCHAR(40) NOT NULL,place VARCHAR(40) NOT NULL,status VARCHAR(12) NOT NULL,expires_at DATETIME NOT NULL,
 INDEX(owner_id,status),INDEX(guest_id,status),INDEX(expires_at),
 FOREIGN KEY(owner_id) REFERENCES users(user_id) ON DELETE CASCADE,FOREIGN KEY(guest_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_badges (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,icon VARCHAR(16) NOT NULL,name VARCHAR(60) NOT NULL,awarded_by INT UNSIGNED NOT NULL,created_at DATETIME NOT NULL,INDEX(user_id),
 FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_rank_suspensions (
 user_id INT UNSIGNED NOT NULL PRIMARY KEY,until DATETIME NOT NULL,reason VARCHAR(200) NOT NULL DEFAULT '',created_by INT UNSIGNED NOT NULL,created_at DATETIME NOT NULL,
 FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_applications (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,service VARCHAR(30) NOT NULL,name VARCHAR(80) NOT NULL,contact VARCHAR(80) NOT NULL,city VARCHAR(40) NOT NULL DEFAULT '',message VARCHAR(600) NOT NULL DEFAULT '',
 status VARCHAR(12) NOT NULL DEFAULT 'pending',admin_note VARCHAR(300) NOT NULL DEFAULT '',created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX(user_id),INDEX(status,created_at),
 FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_restaurants (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,city VARCHAR(40) NOT NULL,name VARCHAR(80) NOT NULL,icon VARCHAR(16) NOT NULL DEFAULT '🍽',district VARCHAR(80) NOT NULL DEFAULT '',description VARCHAR(300) NOT NULL DEFAULT '',
 menu TEXT NOT NULL,order_link VARCHAR(300) NOT NULL DEFAULT '',wechat_id VARCHAR(40) NOT NULL DEFAULT '',whatsapp VARCHAR(20) NOT NULL DEFAULT '',active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX(city,active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_gestures (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,sender_id INT UNSIGNED NOT NULL,target_id INT UNSIGNED NULL,city VARCHAR(80) NOT NULL,place VARCHAR(80) NOT NULL,phrase VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_chinalife_gestures_room(city,place,created_at),CONSTRAINT fk_chinalife_gestures_sender FOREIGN KEY(sender_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_restaurant_places (
 restaurant_id INT UNSIGNED NOT NULL PRIMARY KEY,near VARCHAR(40) NOT NULL,
 CONSTRAINT fk_chinalife_restaurant_places FOREIGN KEY(restaurant_id) REFERENCES chinalife_restaurants(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_ads (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,title VARCHAR(80) NOT NULL,sponsor VARCHAR(80) NOT NULL DEFAULT '',city VARCHAR(40) NOT NULL DEFAULT '',place VARCHAR(40) NOT NULL DEFAULT 'night',link VARCHAR(300) NOT NULL DEFAULT '',
 image MEDIUMBLOB NOT NULL,mime VARCHAR(20) NOT NULL,width SMALLINT UNSIGNED NOT NULL,height SMALLINT UNSIGNED NOT NULL,active TINYINT(1) NOT NULL DEFAULT 1,
 starts_at DATETIME NOT NULL,ends_at DATETIME NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX(place,active,ends_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_media (
 id CHAR(24) NOT NULL PRIMARY KEY,user_id INT UNSIGNED NOT NULL,mime VARCHAR(20) NOT NULL,width SMALLINT UNSIGNED NOT NULL,height SMALLINT UNSIGNED NOT NULL,bytes MEDIUMBLOB NOT NULL,created_at DATETIME NOT NULL,
 INDEX(user_id,created_at),CONSTRAINT fk_chinalife_media_user FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_submissions (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,kind VARCHAR(12) NOT NULL,city VARCHAR(40) NOT NULL,title VARCHAR(80) NOT NULL,data MEDIUMTEXT NOT NULL,
 status VARCHAR(12) NOT NULL DEFAULT 'pending',admin_note VARCHAR(300) NOT NULL DEFAULT '',listing VARCHAR(40) NOT NULL DEFAULT '',reviewed_by INT UNSIGNED NULL,reviewed_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,
 INDEX(status,created_at),INDEX(user_id),CONSTRAINT fk_chinalife_submissions_user FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_songs (
 id CHAR(16) NOT NULL PRIMARY KEY,user_id INT UNSIGNED NOT NULL,title VARCHAR(80) NOT NULL,file VARCHAR(40) NOT NULL,mime VARCHAR(20) NOT NULL,bytes INT UNSIGNED NOT NULL,duration SMALLINT UNSIGNED NOT NULL,
 listing_id INT UNSIGNED NULL,active TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,INDEX(active,listing_id),INDEX(user_id),
 CONSTRAINT fk_chinalife_songs_user FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chinalife_politics_candidates (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,city VARCHAR(40) NOT NULL,office VARCHAR(40) NOT NULL,candidate_id INT UNSIGNED NOT NULL,statement VARCHAR(600) NOT NULL,status VARCHAR(12) NOT NULL DEFAULT 'pending',created_at DATETIME NOT NULL,reviewed_at DATETIME NULL,UNIQUE KEY one_candidate(city,office,candidate_id),INDEX(city,office,status),FOREIGN KEY(candidate_id) REFERENCES users(user_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
