<?php
declare(strict_types=1);
// CLI only: creates push-config.php with this server's VAPID keys (run once).
if (PHP_SAPI !== 'cli') {http_response_code(404);exit;}
$file=__DIR__.'/push-config.php';
if (is_file($file)&&!in_array('--force',$argv,true)) {fwrite(STDERR,"push-config.php already exists. Use --force to replace it (existing subscriptions stop working).\n");exit(1);}
$key=openssl_pkey_new(['curve_name'=>'prime256v1','private_key_type'=>OPENSSL_KEYTYPE_EC]);
openssl_pkey_export($key,$pem);$d=openssl_pkey_get_details($key);
$b64=fn(string $s)=>rtrim(strtr(base64_encode($s),'+/','-_'),'=');
$public=$b64("\x04".str_pad($d['ec']['x'],32,"\0",STR_PAD_LEFT).str_pad($d['ec']['y'],32,"\0",STR_PAD_LEFT));
$subject=$argv[1]??'mailto:admin@hafrik.com';if (str_starts_with($subject,'--')) $subject='mailto:admin@hafrik.com';
file_put_contents($file,"<?php\n// Generated by push-setup.php. Keep private; not in git.\nreturn ".var_export(['public'=>$public,'private_pem'=>$pem,'subject'=>$subject],true).";\n");
chmod($file,0640);
echo "Push keys created in push-config.php\n";
