async function mediaRoute(request,db,identity,url){const id=identity.id,path=url.pathname,method=request.method;
 if(path==='/api/voice'&&method==='DELETE'){const input=await body(request);await db.prepare('DELETE FROM voice_members WHERE user_id = ? AND session = ?').bind(id,input.session).run();await db.prepare('DELETE FROM voice_signals WHERE (sender_id = ? AND sender_session = ?) OR (target_id = ? AND target_session = ?)').bind(id,input.session,id,input.session).run();return reply({ok:true})}
 if(path==='/api/voice'&&method==='POST'){
  const input=await body(request);await activeVenue(db,id,input.city,input.place);input.place=await scopedPlace(input.place,id);if(typeof input.session!=='string'||!/^[a-zA-Z0-9-]{8,80}$/.test(input.session)||typeof input.muted!=='boolean'||!Number.isInteger(input.after)||input.after<0)fail('Invalid voice session.');const now=Date.now();
  let result;if(input.action==='join')result=await db.prepare('INSERT INTO voice_members (user_id, session, city, place, muted, seen_at) SELECT ?, ?, ?, ?, ?, ? WHERE (SELECT count(*) FROM voice_members WHERE city = ? AND place = ? AND seen_at > ? AND user_id != ?) < 4 ON CONFLICT(user_id) DO UPDATE SET session = excluded.session, city = excluded.city, place = excluded.place, muted = excluded.muted, seen_at = excluded.seen_at').bind(id,input.session,input.city,input.place,input.muted?1:0,now,input.city,input.place,now-15000,id).run();else if(input.action==='pulse')result=await db.prepare('UPDATE voice_members SET muted = ?, seen_at = ? WHERE user_id = ? AND session = ? AND city = ? AND place = ? AND seen_at > ?').bind(input.muted?1:0,now,id,input.session,input.city,input.place,now-15000).run();else fail('Choose join or pulse.');if(!result.meta?.changes&&input.action==='pulse')fail('Voice session expired. Join again.',403);if(!result.meta?.changes)fail('This voice room already has four participants.',409);
  const members=await db.prepare('SELECT p.public_id AS id, p.sim_name AS name, v.session, v.muted FROM voice_members v JOIN player_profiles p ON p.user_id = v.user_id JOIN city_presence c ON c.user_id = v.user_id AND c.city = v.city AND c.place = v.place AND c.seen_at > ? WHERE v.city = ? AND v.place = ? AND v.seen_at > ? AND NOT EXISTS (SELECT 1 FROM player_blocks b WHERE (b.owner_id = ? AND b.peer_id = v.user_id) OR (b.owner_id = v.user_id AND b.peer_id = ?)) ORDER BY p.public_id').bind(now-60000,input.city,input.place,now-15000,id,id).all();
  const signals=await db.prepare('SELECT s.id, p.public_id AS sender, s.sender_session AS session, s.payload FROM voice_signals s JOIN player_profiles p ON p.user_id = s.sender_id JOIN voice_members v ON v.user_id = s.sender_id AND v.session = s.sender_session WHERE s.target_id = ? AND s.target_session = ? AND s.city = ? AND s.place = ? AND s.id > ? AND s.created_at > ? AND v.city = s.city AND v.place = s.place AND v.seen_at > ? AND NOT EXISTS (SELECT 1 FROM player_blocks b WHERE (b.owner_id = ? AND b.peer_id = s.sender_id) OR (b.owner_id = s.sender_id AND b.peer_id = ?)) ORDER BY s.id LIMIT 100').bind(id,input.session,input.city,input.place,input.after,now-120000,now-15000,id,id).all();
  await db.prepare('DELETE FROM voice_signals WHERE created_at < ? OR (target_id = ? AND target_session = ? AND id <= ?)').bind(now-120000,id,input.session,input.after).run();return reply({members:members.results||[],signals:(signals.results||[]).map(s=>({...s,payload:JSON.parse(s.payload)})),id:await publicIdentity(id)});
 }
 if(path==='/api/voice/signal'&&method==='POST'){
  const input=await body(request);await activeVenue(db,id,input.city,input.place);input.place=await scopedPlace(input.place,id);const peer=await peerProfile(db,input.peer);if(peer.user_id===id||await blocked(db,id,peer.user_id))fail('Voice peer unavailable.',403);await activeVenue(db,peer.user_id,input.city,input.place);const now=Date.now(),sender=await db.prepare('SELECT session FROM voice_members WHERE user_id = ? AND session = ? AND city = ? AND place = ? AND seen_at > ?').bind(id,input.session,input.city,input.place,now-15000).first(),target=await db.prepare('SELECT session FROM voice_members WHERE user_id = ? AND session = ? AND city = ? AND place = ? AND seen_at > ?').bind(peer.user_id,input.peerSession,input.city,input.place,now-15000).first();if(!sender||!target)fail('Both players must join this voice room.',403);const p=input.payload;if(!p||!['offer','answer','candidate'].includes(p.type))fail('Invalid voice signal.');if(p.type!=='candidate'&&(typeof p.sdp!=='string'||p.sdp.length>20000))fail('Invalid session description.');if(p.type==='candidate'&&(!p.candidate||typeof p.candidate.candidate!=='string'||p.candidate.candidate.length>2000))fail('Invalid ICE candidate.');const payload=JSON.stringify(p);if(payload.length>22000)fail('Voice signal is too large.');const count=await db.prepare('SELECT count(*) AS n FROM voice_signals WHERE sender_id = ? AND created_at > ?').bind(id,now-10000).first();if(count.n>=120)fail('Voice signaling is busy. Try again.',429);await db.prepare('INSERT INTO voice_signals (sender_id, sender_session, target_id, target_session, city, place, payload, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').bind(id,input.session,peer.user_id,input.peerSession,input.city,input.place,payload,now).run();return reply({ok:true});
 }
 if(path==='/api/music'&&['GET','POST'].includes(method)){
  const input=method==='POST'?await body(request):Object.fromEntries(url.searchParams);await activeVenue(db,id,input.city,'night');const now=Date.now();await db.prepare("INSERT INTO club_music_state (city, track, started_at) VALUES (?, 'hometown', ?) ON CONFLICT(city) DO NOTHING").bind(input.city,now).run();
  await db.prepare('DELETE FROM club_music_requests WHERE created_at < ?').bind(now-3600000).run();
  if(method==='POST'){if(!CATALOG.tracks.some(t=>t.id===input.track))fail('Choose a track from the DJ catalogue.');const count=await db.prepare('SELECT count(*) AS n FROM club_music_requests WHERE user_id = ?').bind(id).first();if(count.n>=2)fail('You already have two tracks in the queue.',429);const room=await db.prepare('SELECT count(*) AS n FROM club_music_requests WHERE city = ?').bind(input.city).first();if(room.n>=20)fail('The DJ queue is full. Wait for a track to play.',429);await db.prepare('INSERT INTO club_music_requests (id, city, user_id, track, created_at) VALUES (?, ?, ?, ?, ?)').bind(crypto.randomUUID(),input.city,id,input.track,now).run()}
  await db.prepare("UPDATE club_music_state SET track = COALESCE((SELECT track FROM club_music_requests WHERE city = ? ORDER BY created_at, id LIMIT 1), track), request_id = (SELECT id FROM club_music_requests WHERE city = ? ORDER BY created_at, id LIMIT 1), started_at = ? WHERE city = ? AND started_at <= ?").bind(input.city,input.city,now,input.city,now-60000).run();const state=await db.prepare('SELECT track, request_id, started_at FROM club_music_state WHERE city = ?').bind(input.city).first();if(state.request_id)await db.prepare('DELETE FROM club_music_requests WHERE id = ?').bind(state.request_id).run();const queue=await db.prepare('SELECT r.id, r.track, p.sim_name AS name FROM club_music_requests r JOIN player_profiles p ON p.user_id = r.user_id WHERE r.city = ? ORDER BY r.created_at, r.id LIMIT 20').bind(input.city).all();return reply({track:state.track,startedAt:state.started_at,serverTime:now,queue:queue.results||[]});
 }
 return null;
}
