const pairOf=(a,b)=>[a,b].sort().join(':');
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
async function publicIdentity(id){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(id));return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('').slice(0,20)}
async function blocked(db,a,b){return !!await db.prepare('SELECT id FROM player_blocks WHERE (owner_id = ? AND peer_id = ?) OR (owner_id = ? AND peer_id = ?) LIMIT 1').bind(a,b,b,a).first()}
async function peerProfile(db,id){if(typeof id!=='string'||!/^[a-f0-9]{20}$/.test(id))fail('Choose a valid player.');const peer=await db.prepare('SELECT user_id, public_id, sim_name, color FROM player_profiles WHERE public_id = ?').bind(id).first();if(!peer)fail('Player profile unavailable.',404);return peer}
const privateResidence=place=>place==='home'||place.startsWith('home-');
async function scopedPlace(place,id){const base=place.split('@')[0];return privateResidence(base)?base+'@'+await publicIdentity(id):place}
async function activeVenue(db,id,city,place){const base=place.split('@')[0];if(!Object.keys(CITY_DATA).includes(city)||!L.some(p=>p[0]===base))fail('Choose a valid city venue.');const scoped=await scopedPlace(base,id);if(place.includes('@')&&place!==scoped)fail('This home is private.',403);const presence=await db.prepare('SELECT sim_name FROM city_presence WHERE user_id = ? AND city = ? AND place = ? AND seen_at > ?').bind(id,city,scoped,Date.now()-60000).first();if(!presence)fail('Join the shared city in this venue to chat.',403);return presence}
async function channelFor(db,id,input){if(input.channel==='venue'){await activeVenue(db,id,input.city,input.place);return {channel:'venue',room:input.city+':'+await scopedPlace(input.place,id)}}if(input.channel==='direct'){const peer=await peerProfile(db,input.peer);if(peer.user_id===id)fail('Choose another player.');if(await blocked(db,id,peer.user_id))fail('This conversation is unavailable.',403);const room=pairOf(id,peer.user_id),edge=await db.prepare('SELECT status FROM friendships WHERE pair_key = ?').bind(room).first();if(edge?.status!=='accepted')fail('Accept a friend request before private messaging.',403);return {channel:'direct',room}}fail('Choose a conversation.')}
async function visibleMessage(db,id,message){if(!message)fail('Message unavailable.',404);if(message.channel==='venue'){const [city,place]=message.room.split(':');await activeVenue(db,id,city,place);if(await blocked(db,id,message.sender_id))fail('Message unavailable.',404)}else{const edge=await db.prepare('SELECT first_id, second_id, status FROM friendships WHERE pair_key = ?').bind(message.room).first();if(edge?.status!=='accepted'||![edge.first_id,edge.second_id].includes(id))fail('Message unavailable.',404);if(await blocked(db,edge.first_id,edge.second_id))fail('Message unavailable.',404)}}
async function socialRoute(request,db,identity,url){const id=identity.id,path=url.pathname,method=request.method;
 if(path==='/api/social'&&method==='GET'){
  const result=await db.prepare('SELECT p.public_id AS id, p.sim_name AS name, p.color, f.status, CASE WHEN f.requested_by = ? THEN 1 ELSE 0 END AS outgoing, c.city, c.place, c.seen_at FROM friendships f JOIN player_profiles p ON p.user_id = CASE WHEN f.first_id = ? THEN f.second_id ELSE f.first_id END LEFT JOIN city_presence c ON c.user_id = p.user_id WHERE (f.first_id = ? OR f.second_id = ?) AND NOT EXISTS (SELECT 1 FROM player_blocks b WHERE (b.owner_id = ? AND b.peer_id = p.user_id) OR (b.owner_id = p.user_id AND b.peer_id = ?)) ORDER BY f.created_at DESC LIMIT 100').bind(id,id,id,id,id,id).all();
  const blocks=await db.prepare('SELECT p.public_id AS id, p.sim_name AS name, p.color FROM player_blocks b JOIN player_profiles p ON p.user_id = b.peer_id WHERE b.owner_id = ?').bind(id).all();return reply({friends:(result.results||[]).map(p=>({...p,place:p.place&&privateResidence(p.place.split('@')[0])?'private-home':p.place,online:!!p.seen_at&&p.seen_at>Date.now()-60000,seen_at:undefined})),blocked:blocks.results||[]});
 }
 if(path==='/api/friends'&&method==='POST'){
  const input=await body(request),peer=await peerProfile(db,input.peer);if(peer.user_id===id)fail('You cannot send yourself a friend request.');if(await blocked(db,id,peer.user_id))fail('This player is unavailable.',403);const key=pairOf(id,peer.user_id),edge=await db.prepare('SELECT requested_by, status FROM friendships WHERE pair_key = ?').bind(key).first();
  if(input.action==='request'){
   const me=await db.prepare('SELECT public_id FROM player_profiles WHERE user_id = ?').bind(id).first();if(!me)fail('Join the shared city to create your player profile.',403);if(edge)return reply({status:edge.status});const count=await db.prepare("SELECT count(*) AS n FROM friendships WHERE requested_by = ? AND status = 'pending'").bind(id).first();if(count.n>=20)fail('You have 20 pending invitations. Wait for responses first.',429);
   const [first,second]=[id,peer.user_id].sort();await db.prepare("INSERT INTO friendships (pair_key, first_id, second_id, requested_by, status, created_at) VALUES (?, ?, ?, ?, 'pending', ?) ON CONFLICT(pair_key) DO NOTHING").bind(key,first,second,id,Date.now()).run();return reply({status:'pending'});
  }
  if(input.action==='accept'){if(!edge||edge.status!=='pending'||edge.requested_by===id)fail('Only the recipient can accept this invitation.',403);await db.prepare("UPDATE friendships SET status = 'accepted' WHERE pair_key = ? AND requested_by != ? AND status = 'pending'").bind(key,id).run();return reply({status:'accepted'})}
  if(['decline','remove','cancel'].includes(input.action)){await db.prepare('DELETE FROM friendships WHERE pair_key = ?').bind(key).run();return reply({ok:true})}fail('Choose a valid friendship action.');
 }
 if(path==='/api/block'&&method==='POST'){const input=await body(request),peer=await peerProfile(db,input.peer);if(peer.user_id===id)fail('Choose another player.');if(typeof input.blocked!=='boolean')fail('Choose block or unblock.');if(input.blocked){await db.prepare('INSERT INTO player_blocks (id, owner_id, peer_id) VALUES (?, ?, ?) ON CONFLICT(id) DO NOTHING').bind(id+':'+peer.user_id,id,peer.user_id).run();await db.prepare('DELETE FROM friendships WHERE pair_key = ?').bind(pairOf(id,peer.user_id)).run()}else await db.prepare('DELETE FROM player_blocks WHERE owner_id = ? AND peer_id = ?').bind(id,peer.user_id).run();return reply({ok:true})}
 if(path==='/api/messages'&&method==='GET'){
  const input=Object.fromEntries(url.searchParams),channel=await channelFor(db,id,input);const rows=await db.prepare('SELECT m.id, p.public_id AS player_id, p.sim_name AS name, p.color, m.body, m.created_at, CASE WHEN m.sender_id = ? THEN 1 ELSE 0 END AS own FROM chat_messages m JOIN player_profiles p ON p.user_id = m.sender_id WHERE m.channel = ? AND m.room = ? AND m.created_at > ? AND NOT EXISTS (SELECT 1 FROM player_blocks b WHERE (b.owner_id = ? AND b.peer_id = m.sender_id) OR (b.owner_id = m.sender_id AND b.peer_id = ?)) ORDER BY m.created_at DESC, m.id DESC LIMIT 50').bind(id,channel.channel,channel.room,Date.now()-7*86400000,id,id).all();return reply({messages:(rows.results||[]).reverse()});
 }
 if(path==='/api/messages'&&method==='POST'){
  const input=await body(request),channel=await channelFor(db,id,input);if(typeof input.text!=='string'||!input.text.trim()||input.text.length>400)fail('Write a message between 1 and 400 characters.');const count=await db.prepare('SELECT count(*) AS n FROM chat_messages WHERE sender_id = ? AND created_at > ?').bind(id,Date.now()-10000).first();if(count.n>=5)fail('Too many messages. Wait a few seconds.',429);const key=crypto.randomUUID();await db.prepare('INSERT INTO chat_messages (id, sender_id, channel, room, body, created_at) VALUES (?, ?, ?, ?, ?, ?)').bind(key,id,channel.channel,channel.room,input.text.trim(),Date.now()).run();await db.prepare('DELETE FROM chat_messages WHERE created_at < ?').bind(Date.now()-7*86400000).run();return reply({ok:true,id:key});
 }
 if(path==='/api/messages'&&method==='DELETE'){const key=url.searchParams.get('id');if(!key)fail('Choose a message.');const result=await db.prepare('DELETE FROM chat_messages WHERE id = ? AND sender_id = ?').bind(key,id).run();if(!result.meta?.changes)fail('Only your own messages can be deleted.',403);return reply({ok:true})}
 if(path==='/api/report'&&method==='POST'){const input=await body(request);if(typeof input.message!=='string'||typeof input.reason!=='string'||!['spam','harassment','inappropriate','other'].includes(input.reason))fail('Choose a message and reason.');const message=await db.prepare('SELECT sender_id, channel, room, body FROM chat_messages WHERE id = ?').bind(input.message).first();await visibleMessage(db,id,message);if(message.sender_id===id)fail('Use delete for your own message.');const key=id+':'+input.message;await db.prepare('INSERT INTO chat_reports (id, reporter_id, message_id, reason, created_at, message_body, sender_id) VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO NOTHING').bind(key,id,input.message,input.reason,Date.now(),message.body,message.sender_id).run();return reply({ok:true})}
 return null;
}
